### ISSUE TITLE
为什么客户端上不显示增加规则的编辑按钮？

### ISSUE THREAD

**Issue by colemanlee** [lazy-luo/smarGate#10]
**Describe the bug**
服务端上线后，为什么客户端上不显示增加规则的编辑按钮？

**Screenshots**
![PIC__4](https://user-images.githubusercontent.com/10258421/70292163-54404000-1818-11ea-84f9-b4915be93e78.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 version 1909

**Comment by lazy-luo** [comment]
关闭“自动刷新”开关，进入编辑模式

**Comment by lazy-luo** [comment]
如果在模拟器中运行，注意网络需要打通，否则外部无法访问客户端配置的转发端口。
