### ISSUE TITLE
【寻求帮助】如何在电脑上配置客户端？

### ISSUE THREAD

**Issue by fatinghenji** [lazy-luo/smarGate#100]
RT，举例我想在我电脑上搭建一个mc服务器，然后我希望在我公司的电脑上可以访问，我应该如填写公司电脑的配置文件呢？

**Comment by lazy-luo** [comment]
SG客户端只有Android版，原因是服务端不需要运行客户端。
你的场景，只需要在APP上配置服务端间映射就可以了，具体如下

1、分别在mc服务器及公司电脑上分别运行SG服务端（假设mc服务器上SG服务端序号为1，公司电脑SG服务端序号为2）
2、登录app，可以分别看到序号为1和2的“访问点”
3、编辑模式下，在序号为2的“访问点”（公司电脑）上配置指向序号为1的服务端间端口映射，配置如下（假设想将公司电脑3333端口映射到mc服务器4444端口，协议tcp）：3333    localhost@1    4444    TCP
4、配置完成后，切换到正常模式，稍等一会（隔20秒刷新状态），当看刚才配置的映射生效后就可以直接在公司电脑上通过localhost:3333访问到mc服务器的4444端口了。

注意：
1、公司电脑到APP必须能P2P（或有自定义代理）的情况下，才会显示服务端间代理状态，否则不显示状态
2、公司电脑到mc服务器间必须能打通P2P（或有自定义代理），服务端间连接才真正生效

**Comment by fatinghenji** [comment]
感谢！
