### ISSUE TITLE
windows服务端掉线

### ISSUE THREAD

**Issue by GitKUPER** [lazy-luo/smarGate#101]
经测试0.32.1之后的两个版本，在windows上部署服务端，app端隔段时间就不显示接入点了，刷新多次或杀后台重启APP依然没有，查看windows任务管理器进程是在的，只能重启进程，之前版本有时也会不显示但重启几次app就刷出来了。

**Comment by zhouhuade** [comment]
这是来自本邮箱的自动回复邮件。你好，我已收到你的邮件，我将尽快给你回复。

**Comment by lazy-luo** [comment]
APP显示问题存在bug，请关注app提交变化，重新下载

**Comment by GitKUPER** [comment]
> APP显示问题存在bug，请关注app提交变化，重新下载

不是说app设置的映射不显示，而是服务端离线，两台windows服务器分别跑一个服务端，过段时间比如到了明天，2就离线了app刷不出来了(服务器上进程依然在)，因为之前把1升级了新版本发现有这个问题，所以现在1还是用的老版本就没这个问题。是这个意思![IMG_20240201_163301.jpg](https://github.com/lazy-luo/smarGate/assets/102667024/aeac7ade-68b0-4227-bfae-b949a1a55e61)
