### ISSUE TITLE
安装app失败，解析包出现问题

### ISSUE THREAD

**Issue by yh110224** [lazy-luo/smarGate#102]
2024年2月1日下载最新包，安装时报错
[INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl1275140629.tmp/base.apk: AndroidManifest.xml]

**Comment by lazy-luo** [comment]
请重新下载试试

**Comment by yh110224** [comment]
2024-2-1 14:25:48下载最新包，还是出现同样的问题。
安卓版本7.1.1

**Comment by lazy-luo** [comment]
sg最低兼容andorid5.1，至于你的设备无法安装，没有具体详细信息，目前无法排查
