### ISSUE TITLE
Windows版的服务端异常持续占用25%的CPU资源

### ISSUE THREAD

**Issue by licheedev** [lazy-luo/smarGate#103]
系统环境是unraid上虚拟的Windows7旗舰版64位，j4125 4个核心全部启用，内存分配4G。
服务端版本是最新的windows_x86v0.32.3，运行参数使用教程的
> proxy_server.exe -i1000 -o1000 -w8

服务端运行一段时间后，在空闲情况下，有几率会出现服务端进程持续占用25%CPU资源，不会升高也不会降低，只能通过杀进程解决。
我是昨天下午才部署的服务端，这种持续占用25%CPU的情况，已经出现过两次。

![1](https://github.com/lazy-luo/smarGate/assets/10960780/0e491a7f-7681-4e45-bef6-28ade8d450f6)
![2](https://github.com/lazy-luo/smarGate/assets/10960780/0d8a18b0-7d58-46bd-bda4-cdd5f4abec0a)

**Comment by lazy-luo** [comment]
可以留意一下具体复现的操作，便于排查问题

**Comment by licheedev** [comment]
> 可以留意一下具体复现的操作，便于排查问题

昨天看到服务端有新的提交，我试着替换了下重新运行了大半天，暂时没复现25%占用的问题，但看着版本号没变，不晓得是不是程序修复了。
还有不知道跟网速有没有关系，所在的出租屋共用一条宽带，邻居不知道做了什么，他一下班回来网就很容易卡，卡到连打开个百度都失败的那种，前晚出现25%占用的时候，网就卡过一阵，不过昨天网很流畅，可能邻居回家过年了。

**Comment by lazy-luo** [comment]
> > 可以留意一下具体复现的操作，便于排查问题
> 
> 昨天看到服务端有新的提交，我试着替换了下重新运行了大半天，暂时没复现25%占用的问题，但看着版本号没变，不晓得是不是程序修复了。 还有不知道跟网速有没有关系，所在的出租屋共用一条宽带，邻居不知道做了什么，他一下班回来网就很容易卡，卡到连打开个百度都失败的那种，前晚出现25%占用的时候，网就卡过一阵，不过昨天网很流畅，可能邻居回家过年了。

的确，当网络慢发送数据无法确保到达时，系统会尽可能重试，期间cpu会有增高现象，一般这种情况基本不会持续太长时间。建议再观察一下。

**Comment by licheedev** [comment]
> > > 可以留意一下具体复现的操作，便于排查问题
> > 
> > 
> > 昨天看到服务端有新的提交，我试着替换了下重新运行了大半天，暂时没复现25%占用的问题，但看着版本号没变，不晓得是不是程序修复了。 还有不知道跟网速有没有关系，所在的出租屋共用一条宽带，邻居不知道做了什么，他一下班回来网就很容易卡，卡到连打开个百度都失败的那种，前晚出现25%占用的时候，网就卡过一阵，不过昨天网很流畅，可能邻居回家过年了。
> 
> 的确，当网络慢发送数据无法确保到达时，系统会尽可能重试，期间cpu会有增高现象，一般这种情况基本不会持续太长时间。建议再观察一下。

又用了几天，还是有这个25%占用的问题，有时候甚至服务端的进程自动就挂掉。
前几天服务端的进程就挂掉过，因为我宿舍和老家都部署了蒲同英P5，现在回老家了，用不着smarGate，就一直没重启服务端。
几个小时前心血来潮，运行了下服务端，手机切换流量上网，运行smarGate App，用jellyfin看了几个视频(映射的是tcp协议)，然后杀掉了smarGate App，几个小时后，VNC看一下win7虚拟机，果然又25%占用了，这时候启动smarGate App，app上找不到win7虚拟机上的服务端，杀掉服务端进程并重新运行，app上才刷新出服务端。
这时候出租屋的邻居应该都回家过年了，网络很流畅，应该不是网络卡顿的问题。感觉这bug出现得很频繁，P2P打洞成功后，随便看几个视频，杀掉手机app，放置一段时间，就大几率异常占用25%。
![任务管理器](https://github.com/lazy-luo/smarGate/assets/10960780/31ed4ac3-d829-4636-b8d3-c4c3d7355833)
![手机APP截图](https://github.com/lazy-luo/smarGate/assets/10960780/93e218f9-270b-4978-91bf-4a0b52c9e2d2)

**Comment by lazy-luo** [comment]
这种情况请排除一下网络原因，具体来讲除非SG没有收到tcp断开报文，且在已断开连接上发送数据未触发错误，才可能一直重试。建议：
1、排除是否有vpn网络影响
2、如有条件直接在“干净”的物理机上测试一下，看看是否仍然重现

**Comment by lazy-luo** [comment]
windows确有BUG，但难以重现，如有可靠重现步骤，再行排查

**Comment by lazy-luo** [comment]
已修复发现的相关BUG
