### ISSUE TITLE
文件传输问题

### ISSUE THREAD

**Issue by dragon100georg** [lazy-luo/smarGate#105]
手机端刚安装时，可以连接内网端进行文件传输，可以看到是p2p传输，用一段时间P2p就不出现了。无论是重新运行内网端，重启手机端，都看不到文件传输的图标了，无法快速传输文件啦。手机、内网主机都有ipv6，可以v6访问。初始情况下在服务集合后面有个文件传输的按钮，现在怎么也不出现了。
发现问题为手机端多个ipv6地址获取选择错误就没有文件传输了
bug:
1.只有ipv6为 2409:***:***:1793的时候才能出现文件夹。似乎是在ipv6第二个地址正确的时候才会出现，应该是软件ipv6选择错误所致。看历史问题描述，是多重v6地址所致。软件还是没选择对。
2.另外最新版ipv6地址显示不完全，字体大了
3.vivo手机 后台无法锁定，切换app还会掉线。
4.能否适配aarch64

**Comment by dragon100georg** [comment]
发现问题为手机端多个ipv6地址获取选择错误就没有文件传输了

**Comment by lazy-luo** [comment]
1、ipv6地址选择使用首选第一个地址，ipv6下无法p2p有可能是v6地址超时未续租
2、更新版本ipv6地址字体已调整
3、后台无法锁定不属于应用范畴，确保手动授权app后台运行权限及忽略电池优化
4、服务端全平台支持请在dynamic目录下选择对应架构。ARMv8-A架构使用arm64的版本
最后，请务必确保版本为github上最新时间戳
