### ISSUE TITLE
能否加个ddns功能，或者开放android代码

### ISSUE THREAD

**Issue by sqlwwx** [lazy-luo/smarGate#106]

**Comment by lazy-luo** [comment]
1、sg不支持ddns功能，sg可以配置ip和域名。
2、一方面，一直比较忙，代码没有时间梳理，再者SG目前功能不多重点是稳定性和可靠性提升，个人精力尚还满足。如后续有大版本规划时会考虑开源，届时欢迎大家贡献代码。
