### ISSUE TITLE
中兴7610m光猫上执行程序报错ld-linux.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lilyok1234** [lazy-luo/smarGate#107]
大佬，我的环境略为特殊，我是在光猫上执行smargate，运行时报库找不到。用的是arm32的最新的版本

/usr/plugin # proxy_server 
proxy_server: error while loading shared libraries: ld-linux.so.3: cannot open shared object file: No such file or directory

你这个工具很好用，主要是tcp的穿透，之所以要在光猫上跑是因为光猫上的TCP是NAT 1。现在我在光猫上安装了entware环境，按理说这些库都有的。难道是因为它只去系统lib路径找，没有ld-linux.so.3名字只有个ld-linux-armhf.so.3导致？因为系统的rootfs是只读的，更改不了。怎么能让smagate指向opt的entware链接路径呢？

/usr/plugin # ls /lib/ld-*
/lib/ld-2.26.so             /lib/ld-linux-armhf.so.3
/lib/ld-linux-aarch64.so.1

/usr/plugin # ls /opt/lib/ld-*
/opt/lib/ld-2.27.so     /opt/lib/ld-linux.so.3

/usr/plugin # uname -a
Linux F7610M0 4.1.25 #2 SMP Tue Nov 29 23:29:03 CST 2022 aarch64 GNU/Linux

**Comment by lilyok1234** [comment]
想做个软链接也不可以，rootfs主只读的

/lib #  ln -s ld-2.26.so  ld-linux.so.3
ln: ld-linux.so.3: Read-only file system

**Comment by lazy-luo** [comment]
确保下载最新时间戳版本，然后：
1、cd到sg服务端目录
2、运行：ln -s /lib/ld-linux-armhf.so.3 ld-linux.so.3

**Comment by lilyok1234** [comment]
软链接创建不了的，这光猫rootfs是只读的，应该是gcc链接时默认优先使用ld-linux.so.3

https://wenku.csdn.net/answer/6228c869dd6f4e6d8ddfa1fb8bb45b1d

/ # ln -s /lib/ld-linux-armhf.so.3 ld-linux.so.3
ln: ld-linux.so.3: Read-only file system

**Comment by lilyok1234** [comment]
设置链接路径有用，我这个是arm32的cpu，但是还是报错。只能在光猫的下游设备跑smargate了

/usr/plugin # export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/lib
/usr/plugin # ./proxy_server 
./proxy_server: error while loading shared libraries: /opt/lib/libpthread.so.0: internal error

**Comment by lilyok1234** [comment]
大佬能不能搞个静态链接的版本，我的存储空间有30M，应该够的
