### ISSUE TITLE
iStoreos运行arm64版本出错

### ISSUE THREAD

**Issue by surely66** [lazy-luo/smarGate#108]
1、运行环境：iStoreos 22.03.6，安装目录：/root/smargate，是arm64的0.32.3最新版本；
2、安照#41 #32 的说明，查看动态依赖：
      ldd proxy_server
              /lib/ld-linux-aarch64.so.1 (0x7fa2ed6000)
              libpthread.so.0 => /lib/ld-linux-aarch64.so.1 (0x7fa2ed6000)
              libdl.so.2 => /lib/ld-linux-aarch64.so.1 (0x7fa2ed6000)
              libc.so.6 => /lib/ld-linux-aarch64.so.1 (0x7fa2ed6000)
      建立软连接：      ln -s /lib/ld-musl-aarch64.so.1 /lib/ld-linux-aarch64.so.1
3、运行出错：
    root@iStoreOS:~/smargate# ./proxy_server
    no environment-variable "SMS_HOME" define.
    current search/work path: /root/smargate/
    Server config file is: /root/smargate/conf-proxy.xml
    [INFO]  plugin path is:/root/smargate/plugin/
    [WARN]  NOT-FOUND library in :/root/smargate/plugin/
    [WARN]  load plugin module error.
    [INFO]  version of CORE: Linux ARC ARM64 v0.32.3
    
    *****************************NO PLUGIN INFORMATION*****************************
    Segmentation fault

请问怎么处理？

**Comment by zhouhuade** [comment]
这是来自本邮箱的自动回复邮件。你好，我已收到你的邮件，我将尽快给你回复。

**Comment by lazy-luo** [comment]
```
BusyBox v1.35.0 (2023-11-25 18:18:57 UTC) built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt 22.03.6, r20265-f85a79bcb4
 -----------------------------------------------------
```
```
root@OpenWrt:/server# uname -a
Linux OpenWrt 5.10.201 #0 SMP Sat Nov 25 18:18:57 2023 aarch64 GNU/Linux
root@OpenWrt:/server# ldd proxy_server
	/lib/ld-linux-aarch64.so.1 (0x7fba551000)
	libpthread.so.0 => /lib/ld-linux-aarch64.so.1 (0x7fba551000)
	libdl.so.2 => /lib/ld-linux-aarch64.so.1 (0x7fba551000)
	libc.so.6 => /lib/ld-linux-aarch64.so.1 (0x7fba551000)
root@OpenWrt:/server# ln -s /lib/ld-musl-aarch64.so.1 /lib/ld-linux-aarch64.so.1
root@OpenWrt:/server# ./proxy_server
no environment-variable "SMS_HOME" define.
current search/work path: /server/
Server config file is: /server/conf-proxy.xml
[INFO]	plugin path is:/server/plugin/
[WARN]	NOT-FOUND library in :/server/plugin/
[WARN]	load plugin module error.
[INFO]	version of CORE: Linux ARC ARM64 v0.32.3 

*****************************NO PLUGIN INFORMATION*****************************
[INFO] CPU BITS-ORDER is:LITTLE_ENDIAN
[INFO] CPU BYTE-ORDER is:LITTLE_ENDIAN
OpenSSL Ver:0x1010117F
```
未见异常，请确认自己的固件版本
