### ISSUE TITLE
没有Android客户端相关源码提供吗？

### ISSUE THREAD

**Issue by mesoar** [lazy-luo/smarGate#11]
没有Android客户端相关源码提供吗？

**Comment by lazy-luo** [comment]
有开源计划的，取决于工具本身的被认可程度及稳定性。毕竟没有人气的开源没啥动力，本人开源的excel就是一个例证

**Comment by mesoar** [comment]
目前只能通过作者你的服务来进行对吗？不可以自己创建服务以及编译客户端？
有考虑先把客户端提供吗？希望有机会使用到项目并且提供反馈，目前有个需求很接近。

**Comment by lazy-luo** [comment]
认证服务器，主要为toB考虑，提供集中化的鉴权，目前只有一个。数据代理服务器可自建。
目前项目处于初期，主要定位为自用，暂不建议用于生产。
源码开放坚持价值原则，没有用户基数的开源没有驱动力。
