### ISSUE TITLE
没有外网发布示例同时服务端之间的P2P端口映射报错

### ISSUE THREAD

**Issue by ZanePoe** [lazy-luo/smarGate#110]
没有看到外网外网发布的示例。
我有vps，我需要将一些服务发布到vps的公网IP。

我尝试使用服务端之间P2P端口映射来实现此功能，但是报错。
错误信息如下：
![image](https://github.com/lazy-luo/smarGate/assets/16047426/51b5ed18-06f5-4ea1-8991-26e577affd0d)
我的配置如下：
![image](https://github.com/lazy-luo/smarGate/assets/16047426/42a5d17d-8974-460a-a359-e77ab6a3aa43)
我通过手机的ip访问序号3服务所在内网其他终端的ip端口是没有问题的：
![image](https://github.com/lazy-luo/smarGate/assets/16047426/ef546765-d1f6-46a8-92a9-a41c4a65c042)

**Comment by lazy-luo** [comment]
确有此BUG，原因是增加了默认协议TCP，在处理默认选中时存在BUG，已修复，下载更新的版本。
BUG规避方法：打开协议下拉框，重新选中协议
