### ISSUE TITLE
怎么解决

### ISSUE THREAD

**Issue by daimile** [lazy-luo/smarGate#113]
admin@onecloud:/opt/natapp$ nohup ./proxy_server -i1000 -o1000 -w8 >/dev/null &
[2] 16151
admin@onecloud:/opt/natapp$ nohup: 忽略输入重定向错误到标准输出端

[2]-  非法指令            nohup ./proxy_server -i1000 -o1000 -w8 > /dev/null
admin@onecloud:/opt/natapp$ nohup ./proxy_server -i1000 -o1000 -w8 >/dev/null 
nohup: 忽略输入重定向错误到标准输出端
非法指令

**Comment by zhouhuade** [comment]
这是来自本邮箱的自动回复邮件。你好，我已收到你的邮件，我将尽快给你回复。

**Comment by lazy-luo** [comment]
硬件架构？系统版本？
这种情况一般出现在hf（hard fpu）指令不支持，一般是比较老的设备可能没有fpu

**Comment by daimile** [comment]
arm32 玩客云 casaos

**Comment by lazy-luo** [comment]
arm32版本使用hf，要求有fpu芯片

**Comment by lazy-luo** [comment]
可到百度网盘下载，百度网盘arm32版本是sf
