### ISSUE TITLE
玩客云刷armbian，无法运行SG，提示“Floating point exception”

### ISSUE THREAD

**Issue by licheedev** [lazy-luo/smarGate#115]
使用的版本是“linux_arm32v0.40.2.tar”，一开始提示找不到“ld-linux.so.3”，创建链接到“/lib/ld-linux-armhf.so.3”后，再运行就提示“Floating point exception”了。

![1](https://github.com/user-attachments/assets/997ebc95-2d2e-4eb5-85f2-3e48c1143482)
![2](https://github.com/user-attachments/assets/d96c358d-2c82-4f5b-8363-a7ff36e3e970)

**Comment by licheedev** [comment]
armbian刷的这个帖子里面的
> https://www.right.com.cn/forum/thread-8361597-1-1.html
6.7.9和6.1.63内核的都试过，问题完全一样。

**Comment by lazy-luo** [comment]
试试dynamic下“linux_mini_arm32v0.40.2.tar”版本

**Comment by licheedev** [comment]
> 试试dynamic下“linux_mini_arm32v0.40.2.tar”版本

还是不行。
![1](https://github.com/user-attachments/assets/09218a25-3149-45ec-b127-917519615bfb)

配置文件
```xml
<?xml version="1.0" encoding="GBK"?>
<app-config code="PROXY" name="proxy-server">
	<app-parameter>
		<ssl-tunnel-required value="first" /><!-- [ none | first | only ] ,none is default. this option set  P2P tunnel  by SSL or NOT -->
		<ssl-create-certfile value="true" /><!-- [ true | false ],if set true sg-server try to create default cacertfiles while not setted, ps: openssl must be installed -->
		<libssl value="libssl.so" /><!-- need replace. same as /lib/libssl.x or /lib64/libssl.x -->
		<libcrypto value="libcrypto.so" /><!-- need replace. same as /lib/libcrypto.x or /lib64/libcrypto.x -->
	</app-parameter>
	<moudle-parameter>
		<log-level value="LOG_ERROR"/>
		<log-write-mode value="CONSOLE_ONLY"/>
		<app-name value="OneCloud" /><!-- need replace -->
		<app-description value="OneCloud" /><!-- need replace -->
		<user-audit value="xxxxxxxxxxxxxx:3"/><!-- need replace and must is numeric-->
	</moudle-parameter>
</app-config>
```

**Comment by licheedev** [comment]
> 试试dynamic下“linux_mini_arm32v0.40.2.tar”版本

不折腾armbian，改刷openwrt了，“linux_mini_arm32v0.40.2.tar”这个版本能用，把几个依赖文件链接一下就好了，
```bash
ln -s /lib/ld-musl-armhf.so.1 /lib/ld-linux.so.3
ln -s /usr/lib/libssl.so.3 /lib/libssl.so
ln -s /usr/lib/libcrypto.so.3 /lib/libcrypto.so
```
![1](https://github.com/user-attachments/assets/1aab57d7-85e6-47ac-b6ae-0450265811ae)
![2](https://github.com/user-attachments/assets/a2ab43f3-320c-431a-80fd-75036a2a13cb)
