### ISSUE TITLE
远程投屏支持

### ISSUE THREAD

**Issue by lazy-luo** [lazy-luo/smarGate#12]
下个版本计划支持原创投屏，如有类似需求的童鞋讨论一下各自需求。敬请期待。。。

**Comment by lazy-luo** [comment]
暂且搁置，有需求再说。

**Comment by imtianx** [comment]
有什么好的方式支持么，想连接远程的设备，就像局域网直接连在电脑上，可以用 qtscrcpy 进行控制。
