### ISSUE TITLE
怎么确定是p2p?

### ISSUE THREAD

**Issue by jianwei2** [lazy-luo/smarGate#13]
连接之后没有说明里的p2p图标。

**Comment by jianwei2** [comment]
![深度截图_选择区域_20191224205355](https://user-images.githubusercontent.com/9263455/71413957-99c19180-268f-11ea-91e4-2a0717d3ccf8.png)
没有这三个图标，手机和电脑ipv6都是通的

**Comment by lazy-luo** [comment]
没有前两个图标之一就说明p2p失败

**Comment by lazy-luo** [comment]
为了便于解决问题，请帖出详细的网络配置

**Comment by jianwei2** [comment]
> 为了便于解决问题，请帖出详细的网络配置

手机是移动4g网络，家里宽带是移动。两边的ipv6地址都可以ping通.

**Comment by lazy-luo** [comment]
宽带光猫是桥接的吧？这种情况肯定可以使用v6穿透的。服务端系统是windows吗？
仔细检查服务端ip配置，如还有问题，请加VX

**Comment by jianwei2** [comment]
> 宽带光猫是桥接的吧？这种情况肯定可以使用v6穿透的。服务端系统是windows吗？
> 仔细检查服务端ip配置，如还有问题，请加VX

光猫自带的路由，有线直连，深度操作系统。我再检查检查

**Comment by jianwei2** [comment]
![image](https://user-images.githubusercontent.com/9263455/71431152-f2824000-270a-11ea-922c-e44e0799506c.png)

**Comment by lazy-luo** [comment]
如果手机是用移动网络的，估计问题出在服务端。服务端多网卡绑定v6网络时，有可能会取到错误的网卡v6地址，如果是linux系统请使用ifconfig查看，windows使用ipconfig查看，确认是否有这种情况。

**Comment by lazy-luo** [comment]
另外确保app有后台运行权限，否则切后台必定断连

**Comment by jianwei2** [comment]
![image](https://user-images.githubusercontent.com/9263455/71432326-d46d0d80-2713-11ea-80c1-a88ce37cec02.png)
![image](https://user-images.githubusercontent.com/9263455/71432346-f6669000-2713-11ea-8812-7e5afb334af6.png)
日志改为Info，显示上面信息，前面那个是我本地服务端的ip，后面那个不是知道是哪个ip，也不是我手机端的。

**Comment by lazy-luo** [comment]
后面那个为识别的服务端v6ip，所以你服务端肯定有某个网络接口使用的是此v6ip

**Comment by lazy-luo** [comment]
或是手机v6ip

**Comment by jianwei2** [comment]
换了个手机卡，手机的ipv6地址变了，但连接信息还是后面那个ip。

**Comment by lazy-luo** [comment]
1、手机是否安装了类似vpn的软件，有可能会创建虚拟网卡。
2、手机是否为多重网络，目前版本可能存在BUG
如果为2则到网盘地址下载最新版本客户端，此版本已修复多重网络甄别BUG

**Comment by jianwei2** [comment]
> 1、手机是否安装了类似vpn的软件，有可能会创建虚拟网卡。
> 2、手机是否为多重网络，目前版本可能存在BUG
> 如果为2则到网盘地址下载最新版本客户端，此版本已修复多重网络甄别BUG

我手机确实有个vpn软件，卸载掉后，然后后面那个ip变了，但也不是我手机的ipv6，也ping不通。已经从网盘下载了最新版本，显示 是0.23版本。

**Comment by lazy-luo** [comment]
1、排除多处登录的情况
2、查看手机当前ip，看看是否与客户端显示的v4地址匹配，同时看看是否有v6地址
3、网盘下载客户端 & 服务端
种种迹象表明问题出在客户端网络环境上，实在不行换个手机登录试试。

**Comment by jianwei2** [comment]
> 1、排除多处登录的情况
> 2、查看手机当前ip，看看是否与客户端显示的v4地址匹配，同时看看是否有v6地址
> 3、网盘下载客户端 & 服务端
> 种种迹象表明问题出在客户端网络环境上，实在不行换个手机登录试试。

没有多处登录，ipv4地址一致，另外有ipv6地址，我在浏览器查看当前ipv6地址也和手机里的一致。
另外我重启手机后，服务端的那个ipv6就会变一次。手机是安卓10。 晚上回去我找旧手机试试。
能不能把ipv6也显示出来，手机没root权限，查不了网卡相关信息。

**Comment by lazy-luo** [comment]
便于查找问题，临时增加客户端显示ipv6地址。请重新下载网盘版本。“编辑”模式下可查看客户端ipv6地址

**Comment by jianwei2** [comment]
> 便于查找问题，临时增加客户端显示ipv6地址。请重新下载网盘版本。“编辑”模式下可查看客户端ipv6地址
![image](https://user-images.githubusercontent.com/9263455/71439127-5caedb00-2733-11ea-87de-c4ab436f8028.png)
![image](https://user-images.githubusercontent.com/9263455/71439132-63d5e900-2733-11ea-8d90-064fac67b6ba.png)
![image](https://user-images.githubusercontent.com/9263455/71439237-c5965300-2733-11ea-97b6-e5dcedf2291c.png)
![image](https://user-images.githubusercontent.com/9263455/71439248-d1821500-2733-11ea-9c05-6ca38d7d8c9c.png)


安装了，服务端收的就是手机上显示的ipv6。但不是我手机的ipv6。手机浏览器获取的ip和直接查看的ip是一样的。不知道是不是我之前搞vpn，有虚拟网卡。

**Comment by lazy-luo** [comment]
应该是手机虚拟网卡留的后遗症，客户端取错了v6地址所致

**Comment by jianwei2** [comment]
> 应该是手机虚拟网卡留的后遗症，客户端取错了v6地址所致

可否搞个可以自定义ipv6的版本？现在手机不给root，搞不定这个ip啊。

**Comment by lazy-luo** [comment]
自定义v6地址的功能没有意义，毕竟目前能获取的v6地址都是动态的。

**Comment by jianwei2** [comment]
> 自定义v6地址的功能没有意义，毕竟目前能获取的v6地址都是动态的。

兄弟可有好方法，你是用什么方法获取的ipv6，我看看能不能在手机上测试下

**Comment by lazy-luo** [comment]
不管是使用手机网络还是家庭宽带，v6地址都是运营商提供的，前缀是动态的。自定义v6地址是没用的，无法路由。你的问题出在手机终端网络配置上，在其它手机上一般不会存在这种问题。
另外尽管v6地址是动态的，但不影响p2p穿透，因此你不需要记住v6地址的，只需记住客户端显示的v4地址就可以了，当然手机上的应用（如RDP客户端）访问的话直接配置成localhost就可以了，网络切换什么的都不影响

**Comment by jianwei2** [comment]
> 不管是使用手机网络还是家庭宽带，v6地址都是运营商提供的，前缀是动态的。自定义v6地址是没用的，无法路由。你的问题出在手机终端网络配置上，在其它手机上一般不会存在这种问题。
> 另外尽管v6地址是动态的，但不影响p2p穿透，因此你不需要记住v6地址的，只需记住客户端显示的v4地址就可以了，当然手机上的应用（如RDP客户端）访问的话直接配置成localhost就可以了，网络切换什么的都不影响

用工具查了下，手机显示三个 ipv6地址，有一个是真实的

**Comment by lazy-luo** [comment]
你用其它手机试试吧，你手机被vpn污染了：）

**Comment by jianwei2** [comment]
> 你用其它手机试试吧，你手机被vpn污染了：）

可能还真不vpn的问题， 我手机是双卡，禁用一个卡，然后重启 就可以了。vpn走的也是手机自带vpn渠道，应该和vpn没关系。  现在看是和双卡有关系，等你什么时候开源了，大家调调看

**Comment by lazy-luo** [comment]
大多android手机都是双卡的，我用的也是电信+联通双卡4G。打了个小补丁，默认取第一个合法v6地址，你到网盘下载看看是否解决了此问题。

**Comment by jianwei2** [comment]
> 大多android手机都是双卡的，我用的也是电信+联通双卡4G。打了个小补丁，默认取第一个合法v6地址，你到网盘下载看看是否解决了此问题。

目前试了几次，都是可以的了

**Comment by zhangqxgz** [comment]
> 大多android手机都是双卡的，我用的也是电信+联通双卡4G。打了个小补丁，默认取第一个合法v6地址，你到网盘下载看看是否解决了此问题。
大佬，太强了，现在手机和家里基本也普及了ipv6，在没有公网v4ip的情况下这个项目可能是最低成本穿透的解决方案了，关注！

**Comment by 564064202** [comment]
都走手机流量了，挺有流量的呀
