### ISSUE TITLE
建议增加自定义配置文件路径，方便设置系统服务。

### ISSUE THREAD

**Issue by lxmoso21** [lazy-luo/smarGate#18]
建议增加自定义conf-proxy.xml 路径，方便做系统服务，谢谢。

**Comment by lxmoso21** [comment]
建议增加自定义conf-proxy.xml 路径，方便做系统服务，谢谢。

**Comment by lazy-luo** [comment]
下载网盘链接中的服务端，自定义配置文件增加命令行参数 “-f 全路径文件名” ，请测试验证。
