### ISSUE TITLE
在手机开启代理的情况下无法进行p2p连接

### ISSUE THREAD

**Issue by OXERIS** [lazy-luo/smarGate#19]
**Describe the bug**
在手机开启代理的情况下（如v2ray)无法进行p2p连接
开启了自动绕过大陆和局域网ip的分流

设备是三星s10+
系统是andriod 10 ，oneUI 2.0

**Comment by lazy-luo** [comment]
全局代理是走隧道的，客户段连接请求会被你代理服务端转发，因此被识别的地址会变成你代理服务器地址，p2p要求是你客户端NAT出去的地址，因此无法p2p。举个好理解的例子：
小明找小强要钥匙，小强告诉小明“钥匙在左边衣服兜里”，小明直接伸手从小强左边衣兜里拿出钥匙。有代理情况下，小明和小强中间隔了个小芳，小芳只会传达信息，“钥匙在左边衣服兜里”会被转给小明，于是小明直接到小芳左边衣兜里拿钥匙，so 出现你的问题了。

**Comment by OXERIS** [comment]
感谢你如此详细耐心地解答

zhiyong.luo <notifications@github.com> 于 2020年3月24日周二 20:30写道：
