### ISSUE TITLE
关于通过代理上网情况下的使用

### ISSUE THREAD

**Issue by ziloeng** [lazy-luo/smarGate#2]
我遇到这样的情况：服务器所在网络是通过http代理连接外网的，就是需要设置IE全局代理才能上外网，请问smarGate可以增加此种方式的连接功能吗？谢谢

**Comment by lazy-luo** [comment]
http代理采用流量转发模式，内网机器无法连接除http代理服务器外的任意ip：端口。这种情况只能将smarGate放置到http代理服务器上。
smarGate是tcp代理，正常使用的前提条件：所在主机可以直接连接外网任意端口。
