### ISSUE TITLE
有些地方理解不了

### ISSUE THREAD

**Issue by heartnn** [lazy-luo/smarGate#20]
比如readme里写的4g+ipv6，那么手机必须使用移动数据网络才可以吗？

目前我的状况是这样：家中黑群，单位手机可以连宽带的wifi，电脑是使用宽带，和手机是一个局域网，另有一个公网IP的VPS，这种情况如何环境如何搭建？

家里和单位均为NAT，没有公网IP，且运营商不同。

望回复。

**Comment by lazy-luo** [comment]
如果家中有ipv6，那么手机4G肯定可以p2p；
如果单位wifi，就看看NAT类型了，需要自己试试。
如果有VPS，则可以定义私有代理（配置见readme），这样所有数据走VPS转发，速度依赖VPS带宽。

**Comment by heartnn** [comment]
我现在是Zerotier和frp都用着，frp的tcp没事，xtcp可以打通但是和zerotier一样会碰到udp qos，smargate的原理是不是和frp的xtcp模式差不多，只是把udp换成tcp？

另外目前的模式有一点我的台式机怎么连接手机热点？在没有无线网卡的情况下，只能usb网络分享吧，此时我的电脑访问网络，或者后台aria2，不就悲剧了吗。抱歉问了不太相关的问题。

**Comment by lazy-luo** [comment]
1、frp能通过xtcp进行p2p连接，那么SG应该也没啥问题
2、自定义代理，可以理解成Zerotier的“私有moon”
3、sg的原理readme中有交互图，一目了然
4、sg主要是强调“移动性”和“安全性”更多的是考虑到在外的情况下直接手机使用、接笔记本或pad；台式机没有无线网卡的确会有障碍，但互访的方式有很多，可以将手机接入台式机的局域网wifi---总之确保他们在同一个局域网即可（有非app的客户端，主要是tob的）。

**Comment by heartnn** [comment]
在家里测试成功了，明天到公司再试，目前问题是android不能支持1024以下端口，所以smb的445映射后不能在windows下连接，网上搜了一下，改windows注册表也比较麻烦，但是我手机root了，有没有可能改一下手机客户端，请求root权限？

**Comment by lazy-luo** [comment]
window下连接smb非445端口，稍显麻烦；
暂时没有考虑root权限，毕竟sg设计原则本来就是不对运行环境有特殊要求，app权限也是最低要求。
https://github.com/lazy-luo/smarGate/wiki/常用服务穿透配置

**Comment by heartnn** [comment]
明白了，暂时用webdav代替smb了，实在不行还可以ftp。在家试了一下，基本上达到wifi_5g的峰值，稳定在25MB左右。等到公司再试一下，希望可以直接穿透。

**Comment by lazy-luo** [comment]
如果之前frp能稳定p2p穿透，估计问题不大。另外需要注意的是，p2p成功后空闲2分钟左右会断开重连，确保使用的时候p2p连接是活跃的（绿色），否则会走代理。

**Comment by heartnn** [comment]
现在没问题了，只要两边都开DMZ就可以p2p连接，用的Wifi，请问局域网可以upnp映射端口实现不使用dmz吗？

**Comment by lazy-luo** [comment]
readme写的很清楚，在只要不是NAT-4网络，无需更改路由器或防火墙！你这种情况，理论上不开DMZ，不做upnp照样可以P2P，亲自实践一下吧。

**Comment by heartnn** [comment]
单位有时候是PortRestrictedCone，有时是Symmetic，家里一直是Symmetic，意思我明白了，感谢解答。
