### ISSUE TITLE
希望增加手机的服务端

### ISSUE THREAD

**Issue by OXERIS** [lazy-luo/smarGate#23]
我家的电脑由于不会一直开着，所以，如果有Android的服务端，闲置的手机就可以用上了，当然，能增加路由器的服务端就更好了，比如梅林固件就觉得自己很需要。

**Comment by lazy-luo** [comment]
先确认cpu架构吧，目前min下面有各cpu架构的服务端（armv7、arm64、mipsel等）。
由于本人也没有特定固件环境，无法测试，有条件的可以试试是否能用。

**Comment by lazy-luo** [comment]
dynamic下的服务端为动态编译的，需要配置openssl库。
