### ISSUE TITLE
可以编译armv8版吗？

### ISSUE THREAD

**Issue by terrance-m** [lazy-luo/smarGate#24]

**Comment by lazy-luo** [comment]
armv8 架构请下载 dynamic/linux_arm64.tar
需要自行安装openssl，且在配置文件中指定相关库（见配置文件说明）

**Comment by terrance-m** [comment]
好，我试试，谢谢

**Comment by terrance-m** [comment]
> armv8 架构请下载 dynamic/linux_arm64.tar
> 需要自行安装openssl，且在配置文件中指定相关库（见配置文件说明）

好，我试试，谢谢
