### ISSUE TITLE
需要监听哪些端口，能具体说一下吗？因为服务器要开防火墙

### ISSUE THREAD

**Issue by heartnn** [lazy-luo/smarGate#25]
proxy和客户端，tcp udp，入站出站都需要吧，谢谢。

**Comment by lazy-luo** [comment]
额。。。这个需要结合场景吧，科普的话建议先行百度一下。issue中最好提明确的问题。

**Comment by heartnn** [comment]
也就是说连接的时候是通过的哪个端口，tcp或udp应该放行哪些端口？说的不是手机端，是proxy server和客户端。

**Comment by lazy-luo** [comment]
1、服务端（proxy server）不会开放任何常驻监听端口。因此无需在防火墙中进行端口映射。
2、p2p连接时会协商临时随机端口，且有随机密钥，随机端口无法猜测
综上，防火墙无需任何特别配置。

**Comment by heartnn** [comment]
随机的啊，希望能指定一段端口供使用。否则除了我设定的通过端口，其它的都会reject

**Comment by lazy-luo** [comment]
很好的建议，那就增加一个配置吧，默认为随机协商！
配置文件中增加（在<moudle-parameter>中加,xxxxx为自定义协商端口，自己确保不冲突）：
 <moudle-parameter>
		<negotiation-port value="xxxxx" />
                。。。。。
 </moudle-parameter>

请到网盘链接中下载更新，github上暂不更新（未经测试，请自测）

**Comment by lazy-luo** [comment]
很好的建议，那就增加一个配置吧，默认为随机协商！
配置文件中增加（在&lt;moudle-parameter&gt;中加,xxxxx为自定义协商端口，自己确保不冲突）：
&lt;moudle-parameter&gt;
		&lt;negotiation-port value="xxxxx" /&gt;
                。。。。。
&lt;/moudle-parameter&gt;
请到网盘链接中下载更新，github上暂不更新（未经测试，请自测）

**Comment by heartnn** [comment]
已经加入了端口号，暂时没发现什么不良反应。

**Comment by lazy-luo** [comment]
issue确认后请及时close

**Comment by lazy-luo** [comment]
另外补充一下，只需打开tcp端口，udp的不用
