### ISSUE TITLE
可以考虑windows10开机无需登陆自启吗

### ISSUE THREAD

**Issue by zxbutton** [lazy-luo/smarGate#27]
目前尝试在windows10下开机未登录自启动程序，尽管程序可以启动，但是在手机上面并不能搜索到这台机器，开机之后手动执行bat脚本程序可以正常启动使用。

目前windows10开机自启动是这样，其他系统没有测试过

**Comment by lazy-luo** [comment]
1、windows10下请自行百度将应用程序注册为服务的方法。
2、如有条件建议放到树莓派或路由器上

**Comment by Xzhiliu** [comment]
想请问下访问点下的服务集合是将远程的映射到本地，系统状态信息下的服务集合是什么啊

**Comment by zxbutton** [comment]
> 1、windows10下请自行百度将应用程序注册为服务的方法。
> 2、如有条件建议放到树莓派或路由器上

目前是这样，开机未登录自启动程序需要启动，关闭，再启动才能正常，可能第一次，第二次启动占用的内存大小只有1600k，后面正常启动占用的内存大小是2500k左右

现在我是写了一个循环3次重复开启关闭proxy_server，第四次启动就可以正常使用，这是bug吗

**Comment by zxbutton** [comment]
> 想请问下访问点下的服务集合是将远程的映射到本地，系统状态信息下的服务集合是什么啊

问作者。俺也不知道，让作者完善一下readme的说明。。。

**Comment by lazy-luo** [comment]
@zxbutton 
你的情况没遇到过。
1、请确认启动顺序是否在网络启动之后。
2、如果启动脚本是全路径命令，请加-f参数，否则确认从网盘下载最新更新
@Xzhiliu “系统状态信息下的服务集合”代表手机本身代理，目前用处不大，不用配置。

**Comment by zxbutton** [comment]
@lazy-luo 启动顺序是再在网络启动之后，带-f参数我稍后试试，还有个问题，openvpn会影响到proxy_server.exe的使用吗？我运行proxy_server.exe大概2天，今天早上挂了一下openvpn，移动网关可以正常识别，之后我disconnect openvpn，重启移动网关，发现无法正常在app发现我的机器，然后我启动一下openvpn，我的机器就可以出现了，但是后来我重启proxy_server.exe无法复现这个问题

**Comment by lazy-luo** [comment]
1、openvpn如果停止后未删除虚拟网卡，有可能导致服务端识别多重网络出问题（待验证）
2、断开vpn后如果有断网情况，服务端会有大约10秒左右的延迟连接。因此需要等待10左右才能被正常识别

**Comment by zxbutton** [comment]
@lazy-luo 现在配合智能插座基本没什么问题，比较蛋疼是一个账号下多台机器（处于不同网络环境），同时显示只能显示一台吗？
