### ISSUE TITLE
客户端可以请求root权限了，作者给解释一下呗。

### ISSUE THREAD

**Issue by heartnn** [lazy-luo/smarGate#29]
是不是快能映射smb了？
另外之前的版本映射ftp成功了，使用的被动模式，但有些许问题，filezilla会卡在mlcd时错误，服务端局域网是没有问题的，flashfxp可以登录，但是传文件卡在100%的地方且强制结束后文件错误。
我是被动模式映射了5个数据端口和ftp端口。

另外最近一黑屏客户端就退出了，电池模式什么的设置无效，手机上只有webview最近升级过。

**Comment by lazy-luo** [comment]
1、对于已root手机，app启动时会尝试获取root权限，如果允许且成功，则客户端可配置低于1024的端口。否则配置时会提示失败
2、ftp由于需要协商动态端口，在NAT环境中不被支持（局域网中可以），请使用sftp
3、黑屏退出没有遇到过，无法判断。如若java侧crash则再次启动时会有上次崩溃报告。否则就是被系统干掉了
4、请保持版本是最新的，新版本升级如非可用性问题，一般会将更新放到网盘上（注意更新时间）

**Comment by heartnn** [comment]
有一点小问题，我尝试映射445（samba），但是失败，提示端口冲突。
ftp的问题不搞了，以前frp成功率也不高，现在先用webdav了。
退出问题我换一个手机试试。

**Comment by lazy-luo** [comment]
root权限获取存在问题，有空了再修复。

**Comment by lazy-luo** [comment]
网盘下载新版试试，如果root权限还有问题，请将android版本出示一下，希望下个版本能解决

**Comment by heartnn** [comment]
![Screenshot_2020-05-13-09-50-36-262_com android settings](https://user-images.githubusercontent.com/457514/81762587-92483b00-94ff-11ea-8951-687a82ea0028.jpg)  
![Screenshot_2020-05-13-09-51-31-894_com smarGate huawei](https://user-images.githubusercontent.com/457514/81762591-94aa9500-94ff-11ea-883d-a43aaee86976.jpg)

**Comment by lazy-luo** [comment]
@heartnn 综合多方面考虑，现有版本决定暂不支持开放1024以下端口。
