### ISSUE TITLE
MIUI11 android8.0下大概率闪退，用户无法升级webview

### ISSUE THREAD

**Issue by hao86** [lazy-luo/smarGate#3]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lazy-luo** [comment]
请下载网盘最新版本（兼容到android5.1），如问题依然存在，测试后将crash日志贴出来（闪退后第二次打开会显示crash日志）
