### ISSUE TITLE
是不是不支持cpu rk3328

### ISSUE THREAD

**Issue by liyiranlab** [lazy-luo/smarGate#30]
系统armbain，运行命令老提示没有文件或者目录。

**Comment by lazy-luo** [comment]
1、Cortex-A53 系列应该是armv8 64位的，自行确认一下
2、如果1）确认无误，请确认系统是否为linux系
如上确认无误后，请到dynamic目录下找到对应架构的包下载测试。

**Comment by liyiranlab** [comment]
谢谢，找到了，但是提示 nohup: 忽略输入重定向错误到标准输出端，什么意思？

**Comment by liyiranlab** [comment]
手机4g网映射成功了，本地端口50445路由器指向127.0.0.1:445,可以打开目录，但是无法通过smb看视频，为什么？而且好像过一会就连不上了。。。哎

**Comment by lazy-luo** [comment]
1、目前手机无法监听小于1024的端口。
如果是windows的话，smb端口默认只认445；macos可以smb://ip:port 方式指定。
2、确保手机app允许后台运行，否则黑屏或切后台后会断开连接无法使用的。
另外，nohup不用理他，这是xnix系统后台标准姿势

**Comment by liyiranlab** [comment]
我用的是es文件浏览器，127.0.0.1:50445可以打开目录，但是一开视频就好像卡掉线了！另外手机4g网连接好像打不开p2p通道；我主要想连电信网FullCone的nas到移动宽带wifi手机，但是还没有时间去测试是否可以打开p2p通道，是同一城市，希望可用。

**Comment by lazy-luo** [comment]
FullCone肯定是可以的，如有v6地址更好。
仔细看官网说明，根据颜色判断是否p2p成功。无法p2p的场景就别奢望大流量应用的使用感知。掉线问题参见上面的回复。

**Comment by heartnn** [comment]
> 我用的是es文件浏览器，127.0.0.1:50445可以打开目录，但是一开视频就好像卡掉线了！另外手机4g网连接好像打不开p2p通道；我主要想连电信网FullCone的nas到移动宽带wifi手机，但是还没有时间去测试是否可以打开p2p通道，是同一城市，希望可用。

有时打开路由器的dmz会有奇迹出现，把nas和手机分别打开两个路由器的dmz主机，这样会少一层nat，有可能会p2p连接，另外建议查一下路由器的upnp，还有光猫的运行模式。尽量减少nat层，才有可能穿透成功。
