### ISSUE TITLE
能开发支持openwrt吗？

### ISSUE THREAD

**Issue by flywbo** [lazy-luo/smarGate#32]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lazy-luo** [comment]
后续提供，涉及到多架构cpu支持，暂没时间弄交叉编译环境。

**Comment by lazy-luo** [comment]
经验证，现有dynamic下版本支持lede（必须是musl库，之前版本uClibc库不兼容）
使用方式：
1、解压到对应目录（下载对应cpu架构--x86的支持有问题）
2、使用ldd ./proxy_server 查看动态库依赖
3、创建软连接（以x86_64为例）
      ln -s /lib/ld-musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2
4、再次ldd查看是否还有未找到的库，使用3）中方法创建软连接
5、配置&运行
另：alpine下也是一样的做法
