### ISSUE TITLE
不太清楚我理解的对不对，请教使用方法。

### ISSUE THREAD

**Issue by wsysx123** [lazy-luo/smarGate#34]
我现在在云服务器上开启了服务端模式，手机上也成功连接了。看到了云服务器上线了。目前的想法是把手机的adb调试功能映射到服务器上去。路由指向写的127.0.0.1:5555   本地端口写了1234
然后通过手机的adb查看手机确实打开了1234和5555端口。但是云服务器上这两个端口都没有上线。我应该怎样通过云服务器来连接安卓机器的5555端口呢？readme的说明对这一块没有看太懂，还烦请指教一下。谢谢。

**Comment by lazy-luo** [comment]
服务端不会打开任何端口的，sg不是将内网映射到外网。详见“交互模式”图
我猜你可能是想这样做：
想在任意地方（如公司内网）能够连接处于其它地方（如家中）某手机B的5555端口。
做法如下：
1、首先你得有一个手机A用于登陆客户端，然后在手机B上或者手机B所处内网任意设备上安装服务端
2、在A手机客户端上进行你的配置
     a、服务端运行在B手机上的情况：1234 ---》127.0.0.1:5555 
     b、服务端运行在B手机所处内网其它机器上：1234--〉B手机内网IP:5555
3、任意能访问A手机的设备/电脑，使用 “A的IP:1234”访问就可以直接访问到B手机的5555端口了
另外，如果无法P2P的话，建议将云服务器配置成私有代理（和zerotier配置moon一样的效果），手机版服务端不支持私有代理配置，你需要在手机B所处内网其它设备上安装服务端，采用（2中b的配置方式）

**Comment by wsysx123** [comment]
自己折腾好了！原来作者的设计理念是在连接方去设置被连接对象的端口~~之前一直在尝试先在被连接方进行端口的设置在进行连接。通了通了

**Comment by wsysx123** [comment]
emmm， @lazy-luo 回复的好快。谢谢~~

**Comment by imtianx** [comment]
> 自己折腾好了！原来作者的设计理念是在连接方去设置被连接对象的端口~~之前一直在尝试先在被连接方进行端口的设置在进行连接。通了通了

你好，你的这个 adb 的调试具体怎么设置的，可以分享下吗，刚好有这方面的需求。
