### ISSUE TITLE
开机启动需要设置延时，否则无法使用

### ISSUE THREAD

**Issue by hallrady** [lazy-luo/smarGate#36]
树莓派设置开机运行smarGate，需要设置延时启动，否则会失败。
尝试了rc.local脚本和systemd，不设置延时的话，显示已经运行，但实际上无法使用。猜测可能跟默认服务器的通信有关。

**Comment by lazy-luo** [comment]
启动顺序需要在网络模块正常启动之后

**Comment by hallrady** [comment]
是的，其他人避免踩坑 :D

**Comment by eritpchy** [comment]
已经踩坑, 还不得不用上了wait-for-it.sh脚本, 猜测后续断网一段时间也会失联.

**Comment by lazy-luo** [comment]
> 已经踩坑, 还不得不用上了wait-for-it.sh脚本, 猜测后续断网一段时间也会失联.

请更新到最新版本，实测无此问题。
系统加了安全设置，在服务端断电断网等情况无法感知连接断开情况下，服务端最长延迟时间将达到5-10分钟
