### ISSUE TITLE
可以在 OpenWRT 上安装吗？

### ISSUE THREAD

**Issue by GalensGan** [lazy-luo/smarGate#40]
家里是一个软路由，安装了 OpenWRT 系统，系统里面安装了一个网盘，想实现内网穿透，这样在任何地方都可以访问网盘了。
不知道要怎么在 OpenWRT 中安装使用呢？
谢谢！

**Comment by lazy-luo** [comment]
确认一下安装OpenWRT的硬件设备CPU架构，在dynamic中找到相关架构的包即可

**Comment by GalensGan** [comment]
> 确认一下安装OpenWRT的硬件设备CPU架构，在dynamic中找到相关架构的包即可
> 参见：issue #32

好的，多谢
