### ISSUE TITLE
希望开放配置Android客户端小于1024的本地端口，以解决windows局域网共享的转发问题

### ISSUE THREAD

**Issue by OXERIS** [lazy-luo/smarGate#45]
windows局域网共享使用的是smb协议，默认使用445端口
如果想从另一台windows 设备访问windows局域网共享，用于转发的
端口也得是445才行

**Comment by lazy-luo** [comment]
不支持开放1024一下端口，开发保留端口需要root权限，更新历史里有相关原因说明。
可用非windows系统进行访问

**Comment by OXERIS** [comment]
谢谢

zhiyong.luo <notifications@github.com> 于 2021年1月12日周二 13:39写道：
