### ISSUE TITLE
Windows or macOS设备的客户端

### ISSUE THREAD

**Issue by gitLinan** [lazy-luo/smarGate#47]
每次都要带着安卓机 有点奇怪  前提办公室设备都可以分配ipv6 现在使用都是用电脑去访问同一局域网下的安卓设备的ip+端口 可不可以直接适配一套 macOS/Windows的客户端？

**Comment by gitLinan** [comment]
通过几天的使用 发现安卓的客户端 在息屏以后服务会假死 毕竟长时间的工作还是在电脑上  就算已经把APP添加到白名单和后台运行还是会出现这个问题

**Comment by lazy-luo** [comment]
> 每次都要带着安卓机 有点奇怪 前提办公室设备都可以分配ipv6 现在使用都是用电脑去访问同一局域网下的安卓设备的ip+端口 可不可以直接适配一套 macOS/Windows的客户端？

A：其它系统客户端目前仅支持toB场景，免费版本未提供，另外部分原因是后台配置门槛高


> 通过几天的使用 发现安卓的客户端 在息屏以后服务会假死 毕竟长时间的工作还是在电脑上 就算已经把APP添加到白名单和后台运行还是会出现这个问题

A：请描述“假死”具体表现。服务端空闲2分钟左右会自动断开，重连会延迟10-20秒，此间会有时间窗口。如果正在使用，不会断链的。

**Comment by OXERIS** [comment]
同样希望能增加windows的客户端

**Comment by lazy-luo** [comment]
暂时只开放android版的客户端，如果需要在电脑上使用，可采用模拟器。
