### ISSUE TITLE
文档写的看不懂 服务端是局域网

### ISSUE THREAD

**Issue by qian9008** [lazy-luo/smarGate#48]
服务端在局域网，要怎么连接？？？？

**Comment by qian9008** [comment]
也没显示官方代理的地址啊？？？

**Comment by lazy-luo** [comment]
> 服务端在局域网，要怎么连接？？？？

服务端/客户端的要求是需要能上外网即可，至于是否在局域网没有影响



> 也没显示官方代理的地址啊？？？

官方代理默认被内置到客户端/服务端，客户端有“是否使用官方代理”的选项，建议有条件的使用自建代理。
