### ISSUE TITLE
64位win10，proxy_server.exe启动不了是为什么？

### ISSUE THREAD

**Issue by SQQS123** [lazy-luo/smarGate#49]

**Comment by SQQS123** [comment]
![image](https://user-images.githubusercontent.com/32298390/111239638-86079f80-8634-11eb-9bde-d140e6125774.png)

**Comment by SQQS123** [comment]
启动用双击了，没有用说明里的命令……

**Comment by lazy-luo** [comment]
这种一般是conf-proxy.xml配置文件配置有问题
