### ISSUE TITLE
楼主编一个Armbian 的客户端吧

### ISSUE THREAD

**Issue by samondlee** [lazy-luo/smarGate#5]
可以考虑用GO+WEBGUI

手机屏幕长亮撑不住

现在各种随身带的电视盒子  矿渣都能刷armbian了，

所以如果有arm版会很方便。

**Comment by lazy-luo** [comment]
挺好的建议，当然如果是服务端armbian有必要的话。客户端app更能体现移动性；另外手机屏幕不用常量的，android有后台运行权限。。。

**Comment by lazy-luo** [comment]
@samondlee  如果armbian是32位的理论上直接可以使用armv7版本，你可以试试。
