### ISSUE TITLE
最近版本ipv6优先的问题

### ISSUE THREAD

**Issue by heartnn** [lazy-luo/smarGate#50]
假设我的服务器是群晖，客户端为win10，打开wifi和手机在同一局域网

群晖是有ipv6的，且为fullcone  
win10没有ipv6，但也是fullcone

此时，手机打开客户端后，不能使用p2p连接，只能中转。

但是如果把群晖的ipv6关掉后，就可以p2p连接了，**问题就出在这里**。

手机关掉wifi，然后4g，是可以ipv6直通的。

正常来说两边fullcone的话，是完全可以p2p打通的，是不是有点过于依赖ipv6了。

正常情况下，不应该是如果检测不到ipv6，就利用服务器打洞吗？

另外测试过frp，xtcp是可以通p2p的，但是因为udp qos的关系，长时间传输会断掉。

**Comment by lazy-luo** [comment]
这种问题暂时原因不明，主要出现在同一内网内ipv6间偶尔发生，看上去极大可能是内网v6路由寻址出现了问题，此时如果使用4G v6 进行p2p是能成功的，然后再切换到内网v6，此时大多能成功。估计是v6地址路由的问题，比较现在各地v6设备处于测试验证阶段，另外内网ipv6地址是动态的（也有可能临时地址租期过了）。
新版本app端增加了ipv4 only的设置，打开开关，切换一下网络就可以使用v4进行穿透，不用更改服务端网络及设置。

**Comment by heartnn** [comment]
收到，重新测试一下再来反馈。
