### ISSUE TITLE
Openwrt 适配问题

### ISSUE THREAD

**Issue by CoreJK** [lazy-luo/smarGate#51]
阅读后了解到支持 Linux 就忍不住点了个 Start !
请问以后会有计划在 Openwrt 系统上编译为插件么？目前家中主路由正好是 op，想尝试用该方案替代 zerotier～

**Comment by lazy-luo** [comment]
交叉编译环境比较折腾，目前x86架构使用glibc库进行编译。
openwrt上运行目前是可以的，在非glibc环境下，需要将系统依赖库用ln -s 命令创建一下软连接（重命名）：
参见 #37
