### ISSUE TITLE
可以做socks代理吗

### ISSUE THREAD

**Issue by handbye** [lazy-luo/smarGate#52]

**Comment by lazy-luo** [comment]
本身不支持socket5代理，可以配合各种工具一起用

**Comment by handbye** [comment]
您好，可以详细说下吗，还是不清楚该怎么去使用。

**Comment by lazy-luo** [comment]
> 您好，可以详细说下吗，还是不清楚该怎么去使用。
1、找台设备/服务器安装socks5服务端（如ss5），注意最好是将监听地址设为127.0.0.1，端口号自定义如1080
2、在安装ss5的设备上配置启动SG服务端（如访问点名称为ss5）
3、app客户端登录，找到ss5的访问点，配置端口映射：本地端口：1080 远程ip：localhost  远程端口：1080 协议 tcp
4、将socks5代理配置成 app ip：1080即可
配置相见：https://github.com/lazy-luo/smarGate/wiki/快速上手手册

**Comment by zhouhuade** [comment]
这是来自本邮箱的自动回复邮件。你好，我已收到你的邮件，我将尽快给你回复。
