### ISSUE TITLE
HarmonyOS系统，nava5,APP完全退出后，记录的端口信息会清空

### ISSUE THREAD

**Issue by MeditatorV** [lazy-luo/smarGate#53]
本人使用HarmonyOS系统，nava5,当退出APP，后台杀死APP后，再次登录，记录的端口会被清空。需重新输入设置端口才可使用。之前使用的V0.29.1版本没此问题，望改进，谢谢

**Comment by lazy-luo** [comment]
经测试，在HarmonyOS系统上未能重现。为了便于分析请给出详细重现步骤

**Comment by DogReady** [comment]
红米K40，miui13上也有同样的问题。猜测是安卓12收回了一些文件夹读写权限，导致储存的用户信息丢失？

**Comment by zhouhuade** [comment]
这是来自本邮箱的自动回复邮件。你好，我已收到你的邮件，我将尽快给你回复。
