### ISSUE TITLE
Android11 访问点配置完，打开服务端开关，重启app后无响应

### ISSUE THREAD

**Issue by 13237910120** [lazy-luo/smarGate#54]
Android11 配置好访问点，打开服务端开关，重启app后提示无响应
出现机型小米9为anroid 11，身边两台华为手机（鸿蒙系统）没问题 和vivo手机（android 8）没问题

**Comment by 13237910120** [comment]
> > Android11 配置好访问点，打开服务端开关，重启app后提示无响应
> > 出现机型小米9为anroid 11，身边两台华为手机（鸿蒙系统）没问题 和vivo手机（android 8）没问题
> 
> 1、0.3

**Comment by 13237910120** [comment]
> > Android11 配置好访问点，打开服务端开关，重启app后提示无响应
> > 出现机型小米9为anroid 11，身边两台华为手机（鸿蒙系统）没问题 和vivo手机（android 8）没问题
> 
> 1、0.30-0.30.2的版本在android11下会有无响应的情况，0.30.3版本已修复。此bug应该在android11下无法打开应用，你的情况是设置成服务端后无响应，应该不是这种情况 2、排除1中情况，服务端模式下无响应只可，用的是services没有拉起来，等待一会重试一下看看
用的是最新版本，等待一会后仍然无法打开，我试了另外一台Android 11也出现了这种情况，像是在线程中做了耗时操作


> > Android11 配置好访问点，打开服务端开关，重启app后提示无响应
> > 出现机型小米9为anroid 11，身边两台华为手机（鸿蒙系统）没问题 和vivo手机（android 8）没问题
> 
> 1、0.30-0.30.2的版本在android11下会有无响应的情况，0.30.3版本已修复。此bug应该在android11下无法打开应用，你的情况是设置成服务端后无响应，应该不是这种情况 2、排除1中情况，服务端模式下无响应只可能是services没有拉起来，等待一会重试一下看看

感谢回复，我用的确实是最新版本，尝试等待一会后仍然无法打开，我试了另外一台Android 11也出现了这种情况

**Comment by lazy-luo** [comment]
> > > Android11 配置好访问点，打开服务端开关，重启app后提示无响应
> > > 出现机型小米9为anroid 11，身边两台华为手机（鸿蒙系统）没问题 和vivo手机（android 8）没问题
> > 
> > 
> > 1、0.30-0.30.2的版本在android11下会有无响应的情况，0.30.3版本已修复。此bug应该在android11下无法打开应用，你的情况是设置成服务端后无响应，应该不是这种情况 2、排除1中情况，服务端模式下无响应只可能是services没有拉起来，等待一会重试一下看看
> 
> 感谢回复，我用的确实是最新版本，尝试等待一会后仍然无法打开，我试了另外一台Android 11也出现了这种情况

经查，0.30以后的版本支持app服务端语音监听，麦克风权限是默认声明在services上的，在android11以前不授权services能正常启动只是无法监听语音，貌似android11必须手动授权麦克风权限才能启动services。后续把麦克风权限申明从services移除，应该就没这问题了。

**Comment by 13237910120** [comment]
> > > > Android11 配置好访问点，打开服务端开关，重启app后提示无响应
> > > > 出现机型小米9为anroid 11，身边两台华为手机（鸿蒙系统）没问题 和vivo手机（android 8）没问题
> > > 
> > > 
> > > 1、0.30-0.30.2的版本在android11下会有无响应的情况，0.30.3版本已修复。此bug应该在android11下无法打开应用，你的情况是设置成服务端后无响应，应该不是这种情况 2、排除1中情况，服务端模式下无响应只可能是services没有拉起来，等待一会重试一下看看
> > 
> > 
> > 感谢回复，我用的确实是最新版本，尝试等待一会后仍然无法打开，我试了另外一台Android 11也出现了这种情况
> 
> 经查，0.30以后的版本支持app服务端语音监听，麦克风权限是默认声明在services上的，在android11以前不授权services能正常启动只是无法监听语音，貌似android11必须手动授权麦克风权限才能启动services。后续把麦克风权限申明从services移除，应该就没这问题了。
> 
> ps：已移除services上的权限申明，请到网盘（[https://pan.baidu.com/s/14Iq60kxHW711NVoCVKWySg）下载最新修正版（由于没有实际android11设备，请自测）](https://pan.baidu.com/s/14Iq60kxHW711NVoCVKWySg%EF%BC%89%E4%B8%8B%E8%BD%BD%E6%9C%80%E6%96%B0%E4%BF%AE%E6%AD%A3%E7%89%88%EF%BC%88%E7%94%B1%E4%BA%8E%E6%B2%A1%E6%9C%89%E5%AE%9E%E9%99%85android11%E8%AE%BE%E5%A4%87%EF%BC%8C%E8%AF%B7%E8%87%AA%E6%B5%8B%EF%BC%89)

谢谢，测试后ok了
