### ISSUE TITLE
P2P直连性能慢

### ISSUE THREAD

**Issue by lilyok1234** [lazy-luo/smarGate#55]
在本地局域网手机连接树莓派
1、树莓派上跑iperf3 server
2、直接手机用iperf3客户端口测试速度都达到2，300M，此时流量未经过此APP。

同样的环境，
将测速端口tcp5201映射到树莓派的127.0.0.1:5201，流量通过smargate网速降为不到10Mbps的速度了。

测试多次都是一样的结果。显示的是p2p直连状态。我这是个案吗？还是大家都这样，用的最新的30版本。

很好的一个软件

**Comment by lazy-luo** [comment]
树莓派3b+手机，同样的场景：
树莓派：nohup iperf3 -s -p1900 &
树莓派关掉防火墙
1、局域网笔记本iperf3客户端直连树莓派：
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-10.00  sec  39.9 MBytes  33.5 Mbits/sec                  sender
[  5]   0.00-10.00  sec  39.0 MBytes  32.7 Mbits/sec                  receiver

2、局域网笔记本iperf3客户端通过SG访问树莓派：
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-10.00  sec  44.3 MBytes  37.1 Mbits/sec                  sender
[  5]   0.00-10.00  sec  38.7 MBytes  32.5 Mbits/sec                  receiver
测试多次，数据差不多。
没有重现这个问题哦

**Comment by lilyok1234** [comment]
好的，谢谢，晚上下班我再换个手机测试下，看是不是手机的问题

**Comment by lilyok1234** [comment]
我又做了以下测试：
1、更换一部手机MI6，（第一部测试的手机是realme q2）问题依旧，手机端使用的测试软件是pingtools4.52 pro（里面有个性能测试。还是在家里的wifi测试。每次都超不过10Mbps。
2、我又怀疑是我树莓派服务器的问题，又用win10的电脑搭建了一个server，用的公司的wifi。测试还是一样的结果（用的是realme q2手机），不经过smargate时公司的wifi能达到6，70Mbps。
我测速时查看cpu和内存的占用并不高。
请问楼主手机端用的哪个iperf客户端，我用和你一样的来试试。实在是搞不懂了。

**Comment by lazy-luo** [comment]
> 我又做了以下测试：
> 1、更换一部手机MI6，（第一部测试的手机是realme q2）问题依旧，手机端使用的测试软件是pingtools4.52 pro（里面有个性能测试。还是在家里的wifi测试。每次都超不过10Mbps。
> 2、我又怀疑是我树莓派服务器的问题，又用win10的电脑搭建了一个server，用的公司的wifi。测试还是一样的结果（用的是realme q2手机），不经过smargate时公司的wifi能达到6，70Mbps。
> 我测速时查看cpu和内存的占用并不高。
> 请问楼主手机端用的哪个iperf客户端，我用和你一样的来试试。实在是搞不懂了。

直接用笔记本测试的，mac pro 安装iperf3，建议不要用手机版iperf

**Comment by lilyok1234** [comment]
> 
我用win10电脑测试了，10.69.66.115是smargate手机的地址，也差不多。
PS C:\iperf-3.1.3-win64> .\iperf3.exe -c 10.69.66.115 -b 20000000 -n 100000000
[  4] local 10.69.65.129 port 62958 connected to 10.69.66.115 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.00   sec  1.31 MBytes  11.0 Mbits/sec
[  4]   1.00-2.01   sec  1.28 MBytes  10.7 Mbits/sec
[  4]   2.01-3.01   sec  1.34 MBytes  11.3 Mbits/sec
[  4]   3.01-4.00   sec  1.23 MBytes  10.4 Mbits/sec
[  4]   4.00-5.01   sec  1.36 MBytes  11.3 Mbits/sec
[  4]   5.01-6.00   sec  1.34 MBytes  11.3 Mbits/sec
[  4]   6.00-6.08   sec   128 KBytes  12.8 Mbits/sec

**Comment by lilyok1234** [comment]
> > 我又做了以下测试：
> > 1、更换一部手机MI6，（第一部测试的手机是realme q2）问题依旧，手机端使用的测试软件是pingtools4.52 pro（里面有个性能测试。还是在家里的wifi测试。每次都超不过10Mbps。
> > 2、我又怀疑是我树莓派服务器的问题，又用win10的电脑搭建了一个server，用的公司的wifi。测试还是一样的结果（用的是realme q2手机），不经过smargate时公司的wifi能达到6，70Mbps。
> > 我测速时查看cpu和内存的占用并不高。
> > 请问楼主手机端用的哪个iperf客户端，我用和你一样的来试试。实在是搞不懂了。
> 
> 直接用笔记本测试的，mac pro 安装iperf3，建议不要用手机版的压测客户端

发现前几个测试能达到几十M，后面就降速到10M左右了
PS C:\Users\Desktop\iperf-3.1.3-win64> .\iperf3.exe -c 10.69.66.115
Connecting to host 10.69.66.115, port 5201
[  4] local 10.69.65.129 port 63118 connected to 10.69.66.115 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.01   sec  2.88 MBytes  23.9 Mbits/sec
[  4]   1.01-2.01   sec  5.50 MBytes  45.8 Mbits/sec
[  4]   2.01-3.01   sec  4.25 MBytes  36.0 Mbits/sec
[  4]   3.01-4.01   sec  2.38 MBytes  19.7 Mbits/sec
[  4]   4.01-5.00   sec   640 KBytes  5.30 Mbits/sec
[  4]   5.00-6.01   sec  1.62 MBytes  13.5 Mbits/sec
[  4]   6.01-7.01   sec   768 KBytes  6.29 Mbits/sec
[  4]   7.01-8.00   sec  1.38 MBytes  11.7 Mbits/sec
[  4]   8.00-9.00   sec  1.75 MBytes  14.7 Mbits/sec

**Comment by lazy-luo** [comment]
> > > 我又做了以下测试：
> > > 1、更换一部手机MI6，（第一部测试的手机是realme q2）问题依旧，手机端使用的测试软件是pingtools4.52 pro（里面有个性能测试。还是在家里的wifi测试。每次都超不过10Mbps。
> > > 2、我又怀疑是我树莓派服务器的问题，又用win10的电脑搭建了一个server，用的公司的wifi。测试还是一样的结果（用的是realme q2手机），不经过smargate时公司的wifi能达到6，70Mbps。
> > > 我测速时查看cpu和内存的占用并不高。
> > > 请问楼主手机端用的哪个iperf客户端，我用和你一样的来试试。实在是搞不懂了。
> > 
> > 
> > 直接用笔记本测试的，mac pro 安装iperf3，建议不要用手机版的压测客户端
> 
> 发现前几个测试能达到几十M，后面就降速到10M左右了 PS C:\Users\Desktop\iperf-3.1.3-win64> .\iperf3.exe -c 10.69.66.115 Connecting to host 10.69.66.115, port 5201 [ 4] local 10.69.65.129 port 63118 connected to 10.69.66.115 port 5201 [ ID] Interval Transfer Bandwidth [ 4] 0.00-1.01 sec 2.88 MBytes 23.9 Mbits/sec [ 4] 1.01-2.01 sec 5.50 MBytes 45.8 Mbits/sec [ 4] 2.01-3.01 sec 4.25 MBytes 36.0 Mbits/sec [ 4] 3.01-4.01 sec 2.38 MBytes 19.7 Mbits/sec [ 4] 4.01-5.00 sec 640 KBytes 5.30 Mbits/sec [ 4] 5.00-6.01 sec 1.62 MBytes 13.5 Mbits/sec [ 4] 6.01-7.01 sec 768 KBytes 6.29 Mbits/sec [ 4] 7.01-8.00 sec 1.38 MBytes 11.7 Mbits/sec [ 4] 8.00-9.00 sec 1.75 MBytes 14.7 Mbits/sec

确有此问题，之前某个版本在测试小报文时将接收缓存改的较小，目前将其设置到160K大小，一般而言百兆宽带足够了。如果千兆网络的话可以设置的更高些，后续版本考虑增加一个参数自行调整。另：如果带宽还是上不去，请ping一下看看网络时延，另外走SG相当于走代理，局域网测试时相当于双倍带宽占用（非局域网时不存在）。

请从网盘下载最新测试版，附网盘下载地址： https://pan.baidu.com/s/14Iq60kxHW711NVoCVKWySg

**Comment by lilyok1234** [comment]
> > > > 我又做了以下测试：
> > > > 1、更换一部手机MI6，（第一部测试的手机是realme q2）问题依旧，手机端使用的测试软件是pingtools4.52 pro（里面有个性能测试。还是在家里的wifi测试。每次都超不过10Mbps。
> > > > 2、我又怀疑是我树莓派服务器的问题，又用win10的电脑搭建了一个server，用的公司的wifi。测试还是一样的结果（用的是realme q2手机），不经过smargate时公司的wifi能达到6，70Mbps。
> > > > 我测速时查看cpu和内存的占用并不高。
> > > > 请问楼主手机端用的哪个iperf客户端，我用和你一样的来试试。实在是搞不懂了。
> > > 
> > > 
> > > 直接用笔记本测试的，mac pro 安装iperf3，建议不要用手机版的压测客户端
> > 
> > 
> > 发现前几个测试能达到几十M，后面就降速到10M左右了 PS C:\Users\Desktop\iperf-3.1.3-win64> .\iperf3.exe -c 10.69.66.115 Connecting to host 10.69.66.115, port 5201 [ 4] local 10.69.65.129 port 63118 connected to 10.69.66.115 port 5201 [ ID] Interval Transfer Bandwidth [ 4] 0.00-1.01 sec 2.88 MBytes 23.9 Mbits/sec [ 4] 1.01-2.01 sec 5.50 MBytes 45.8 Mbits/sec [ 4] 2.01-3.01 sec 4.25 MBytes 36.0 Mbits/sec [ 4] 3.01-4.01 sec 2.38 MBytes 19.7 Mbits/sec [ 4] 4.01-5.00 sec 640 KBytes 5.30 Mbits/sec [ 4] 5.00-6.01 sec 1.62 MBytes 13.5 Mbits/sec [ 4] 6.01-7.01 sec 768 KBytes 6.29 Mbits/sec [ 4] 7.01-8.00 sec 1.38 MBytes 11.7 Mbits/sec [ 4] 8.00-9.00 sec 1.75 MBytes 14.7 Mbits/sec
> 
> 确有此问题，之前某个版本在测试小报文时将接收缓存改的较小，目前将其设置到160K大小，一般而言百兆宽带足够了。如果千兆网络的话可以设置的更高些，后续版本考虑增加一个参数自行调整。另：如果带宽还是上不去，请ping一下看看网络时延，另外走SG相当于走代理，局域网测试时相当于双倍带宽占用（非局域网时不存在）。
> 
> 请从网盘下载最新测试版（同时更新app和server端），附网盘下载地址： https://pan.baidu.com/s/14Iq60kxHW711NVoCVKWySg 最后，感谢你的反馈！

好的，我试下最新测试版本看看哈，试完给你反馈

**Comment by lilyok1234** [comment]
用最新版本试了下，可以到30Mbps了，有这速度可以了，目前运营商上传也就给3，40，这个bug可以关掉了先

C:\Users\Desktop\iperf-3.1.3-win64>iperf3.exe -c 10.69.66.115
Connecting to host 10.69.66.115, port 5201
[  4] local 10.69.65.129 port 49232 connected to 10.69.66.115 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.01   sec  3.88 MBytes  32.2 Mbits/sec
[  4]   1.01-2.01   sec  3.38 MBytes  28.3 Mbits/sec
[  4]   2.01-3.00   sec  3.88 MBytes  32.7 Mbits/sec
[  4]   3.00-4.00   sec  3.25 MBytes  27.3 Mbits/sec
[  4]   4.00-5.00   sec  3.50 MBytes  29.4 Mbits/sec
[  4]   5.00-6.01   sec  3.38 MBytes  28.0 Mbits/sec
[  4]   6.01-7.01   sec  3.62 MBytes  30.4 Mbits/sec
[  4]   7.01-8.00   sec  3.62 MBytes  30.8 Mbits/sec
[  4]   8.00-9.00   sec  3.50 MBytes  29.3 Mbits/sec
[  4]   9.00-10.00  sec  3.88 MBytes  32.6 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-10.00  sec  35.9 MBytes  30.1 Mbits/sec                  sender
[  4]   0.00-10.00  sec  34.2 MBytes  28.7 Mbits/sec                  receiver

**Comment by lazy-luo** [comment]
> 用最新版本试了下，可以到30Mbps了，有这速度可以了，目前运营商上传也就给3，40，这个bug可以关掉了先
> 
> C:\Users\Desktop\iperf-3.1.3-win64>iperf3.exe -c 10.69.66.115 Connecting to host 10.69.66.115, port 5201 [ 4] local 10.69.65.129 port 49232 connected to 10.69.66.115 port 5201 [ ID] Interval Transfer Bandwidth [ 4] 0.00-1.01 sec 3.88 MBytes 32.2 Mbits/sec [ 4] 1.01-2.01 sec 3.38 MBytes 28.3 Mbits/sec [ 4] 2.01-3.00 sec 3.88 MBytes 32.7 Mbits/sec [ 4] 3.00-4.00 sec 3.25 MBytes 27.3 Mbits/sec [ 4] 4.00-5.00 sec 3.50 MBytes 29.4 Mbits/sec [ 4] 5.00-6.01 sec 3.38 MBytes 28.0 Mbits/sec [ 4] 6.01-7.01 sec 3.62 MBytes 30.4 Mbits/sec [ 4] 7.01-8.00 sec 3.62 MBytes 30.8 Mbits/sec [ 4] 8.00-9.00 sec 3.50 MBytes 29.3 Mbits/sec [ 4] 9.00-10.00 sec 3.88 MBytes 32.6 Mbits/sec
> 
> [ ID] Interval Transfer Bandwidth [ 4] 0.00-10.00 sec 35.9 MBytes 30.1 Mbits/sec sender [ 4] 0.00-10.00 sec 34.2 MBytes 28.7 Mbits/sec receiver

由于部分新增功能未测试，网盘上版本还存在bug，建议先用github上的。我晚上有空了更新一下后再下载

**Comment by lilyok1234** [comment]
> 

好的，收到

**Comment by lazy-luo** [comment]
> 好的，收到

网盘版本已更新
