### ISSUE TITLE
arm64设备4核心开8线程时发现实际只有4线程在工作，且似乎存在内存泄露

### ISSUE THREAD

**Issue by lilyok1234** [lazy-luo/smarGate#56]
环境：
１、使用的是斐讯的n1设备，arm64，4核心，设置的8线程。
./proxy_server -i1000 -o1000 -w8 > /dev/null &
2、测试时发现实际只会用到4线程，我是在测速的时候n1上开着htop看到的，差不多4个核心cpu都快100%，proxy_server有4个线程占用率比较高，但是还有其它4个线程一直是0%
请问下，这是正常的现象吗，像我这种4核心的是不是开4个线程就行？

另外，测速结束后发现内存一直还占用着300多M，也是故意这样设计的吗？

  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command 
14698 root       20   0  164M  2980    36 S  0.0  0.2  0:00.00 (sd-pam)
14796 root       20   0 11096  4876  3208 S  0.0  0.3  0:00.67 -bash
  901 root       20   0  664M  314M  4824 S  0.0 16.9  0:01.21 ./proxy_server -i1000 -o1000 -w8
  902 root       20   0  664M  314M  4824 S  0.0 16.9  0:00.00 ./proxy_server -i1000 -o1000 -w8
 2213 root       20   0  664M  314M  4824 S  0.0 16.9  0:18.37 ./proxy_server -i1000 -o1000 -w8
 2214 root       20   0  664M  314M  4824 S  0.0 16.9  0:00.13 ./proxy_server -i1000 -o1000 -w8
 2215 root       20   0  664M  314M  4824 S  0.0 16.9  0:27.48 ./proxy_server -i1000 -o1000 -w8
 2216 root       20   0  664M  314M  4824 S  0.0 16.9  0:23.98 ./proxy_server -i1000 -o1000 -w8
 2217 root       20   0  664M  314M  4824 S  0.0 16.9  0:25.67 ./proxy_server -i1000 -o1000 -w8
14424 root       20   0  664M  314M  4824 S  0.0 16.9  0:25.86 ./proxy_server -i1000 -o1000 -w8
14426 root       20   0  664M  314M  4824 S  0.0 16.9  0:27.41 ./proxy_server -i1000 -o1000 -w8
16957 root       20   0  664M  314M  4824 S  0.0 16.9  0:25.57 ./proxy_server -i1000 -o1000 -w8
  895 root       20   0  664M  314M  4824 S  0.0 16.9  2:55.75 ./proxy_server -i1000 -o1000 -w8

**Comment by zhouhuade** [comment]
这是来自本邮箱的自动回复邮件。你好，我已收到你的邮件，我将尽快给你回复。

**Comment by lazy-luo** [comment]
请标示一下测试所用的版本。最好将自己的测试场景说明一下
1、有关线程，这个涉及到一些调度策略
a、-w参数配置的是线程池大小，包含快慢事件监测线程（线程数>4时这里会有两个事件线程）及处理线程，因此>4的情况下一般工作线程数量约需要减2（之所以是约，原因是robot线程会根据负荷情况动态调整事件检查线程数量）
b、另外主程序会有1个join主线程，1个robot线程（负责timeout事件及定时内存池回收），这两个线程基本不占cpu
2、内存
a、采用内存池方式使用内存，在高并发下降低内存开销
b、内存是否能被及时释放依赖系统所用的c运行库内存策略，对于glibc一般会每10秒会尝试一下是否可以释放池内空闲内存
c、在linux x86_64/armv7上都做过长时间高并发的疲劳测试，未发现有明显的内存泄露现象

**Comment by lilyok1234** [comment]
> 

不好意思，忘记说了，用的是最新版本v0.30.3，
具体环境是：
1、n1服务器上安装了个测试软件服务端speedtest-x，端口号9001
2、客户端上配置了规则9001端口，路由指向127.0.0.1，端口9001，通过外网的p2p ipv4连接的。
3、然后进行测速，就发现内存一直增大没有释放了。

正常情况下内存占用约300M，现在内存占用一直600M了。
（我这台n1上跑了个v2ray的透明网关，有一些iptables，不知道它影响到了）

  1  [                                                   0.0%]   Hostname: arm-64
  2  [                                                   0.0%]   Tasks: 49, 33 thr; 1 running
  3  [|||||||||||||||||||||||||||||||||||||             66.7%]   Load average: 0.00 0.00 0.00 
  4  [                                                   0.0%]   Uptime: 12:18:33
  Mem[|||||||||||||||||||||||||||||||              625M/1.82G]   Cpu Freq: 1.51 GHz
  Swp[                                                0K/933M]   Eth0 IP: 192.168.6.44
  Cpu Temp:   35 C                                               Eth0 stat: 11.87 KB/s - 4.82 KB/s (TX/RX)

**Comment by lazy-luo** [comment]
试试iperf3，使用iperf3测试场景见 #55 ，多次测试后未发现内存明显增长现象（树莓派，占用8M左右）

**Comment by lilyok1234** [comment]
> 试试iperf3，使用iperf3测试场景见 #55 ，多次测试后未发现内存明显增长现象（树莓派，占用8M左右）

好，我试试，那个bug也是我提的，当时是直连的没怎么注意内存，我用iperf试试，试了结果明天反馈给你

**Comment by lazy-luo** [comment]
> > 试试iperf3，使用iperf3测试场景见 #55 ，多次测试后未发现内存明显增长现象（树莓派，占用8M左右）
> 
> 好，我试试，那个bug也是我提的，当时是直连的没怎么注意内存，我用iperf试试，试了结果明天反馈给你

测试完后确保连接都已断开，对于活动连接sg服务端不会立即释放内存

**Comment by lilyok1234** [comment]
> > > 试试iperf3，使用iperf3测试场景见 #55 ，多次测试后未发现内存明显增长现象（树莓派，占用8M左右）
> > 
> > 
> > 好，我试试，那个bug也是我提的，当时是直连的没怎么注意内存，我用iperf试试，试了结果明天反馈给你
> 
> 测试完后确保连接都已断开，对于活动连接sg服务端不会立即释放内存

我刚刚做了以下测试：
1、用iperf3测试了好几次没有发现内存有明显增长。
2、我重启机器，测试了下speedtest-x，（环境和上面提bug时的一致的）

第一次测试完内存由开机的202----》增长到254M----->过了一会降下来最终为222M，这样还好，也算正常
root@arm-64:~# htop

  1  [||||                                               5.3%]   Hostname: arm-64
  2  [|                                                  0.7%]   Tasks: 48, 30 thr; 1 running
  3  [||                                                 1.3%]   Load average: 0.03 0.15 0.08 
  4  [                                                   0.0%]   Uptime: 00:05:16
  Mem[|||||||||||||                                222M/1.82G]   Cpu Freq: 1.51 GHz
  Swp[                                                0K/933M]   Eth0 IP: 192.168.6.44
  Cpu Temp:   36 C                                               Eth0 stat: 2.26 KB/s - 1.57 KB/s (TX/RX)

  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command 
 2233 root       20   0  162M  4304  1692 S  0.0  0.2  0:00.00 (sd-pam)
 2331 root       20   0 10856  4560  3032 S  0.0  0.2  0:00.21 -bash
  852 root       20   0  404M  7008  4848 S  0.0  0.4  0:00.02 ./proxy_server -i1000 -o1000 -w4
  858 root       20   0  404M  7008  4848 S  0.0  0.4  0:00.00 ./proxy_server -i1000 -o1000 -w4
 2210 root       20   0  404M  7008  4848 S  0.0  0.4  0:00.64 ./proxy_server -i1000 -o1000 -w4
 2211 root       20   0  404M  7008  4848 S  0.0  0.4  0:10.92 ./proxy_server -i1000 -o1000 -w4
 2212 root       20   0  404M  7008  4848 S  0.0  0.4  0:13.22 ./proxy_server -i1000 -o1000 -w4
 2341 root       20   0  404M  7008  4848 S  0.0  0.4  0:13.46 ./proxy_server -i1000 -o1000 -w4
  846 root       20   0  404M  7008  4848 S  0.0  0.4  0:38.32 ./proxy_server -i1000 -o1000 -w4

然后恢复正常，过了一会跑了第二次测试，
系统内存由222M-》增长到了479M，过了很久都没有再降了，smargate显示占用到了255M
root@arm-64:~# htop

  1  [|||||||||||||||||||||||||||||||||||||||||||||||||100.0%]   Hostname: arm-64
  2  [                                                   0.0%]   Tasks: 49, 30 thr; 1 running
  3  [                                                   0.0%]   Load average: 0.03 0.14 0.11 
  4  [                                                   0.0%]   Uptime: 00:12:18
  Mem[|||||||||||||||||||||                        484M/1.82G]   Cpu Freq: 1.51 GHz
  Swp[                                                0K/933M]   Eth0 IP: 192.168.6.44
  Cpu Temp:   35 C                                               Eth0 stat: 8.70 KB/s - 2.03 KB/s (TX/RX)

  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command 
 2233 root       20   0  162M  4304  1692 S  0.0  0.2  0:00.00 (sd-pam)
 2331 root       20   0 10856  4560  3032 S  0.0  0.2  0:00.26 -bash
  852 root       20   0  436M  255M  4848 S  0.0 13.7  0:00.03 ./proxy_server -i1000 -o1000 -w4
  858 root       20   0  436M  255M  4848 S  0.0 13.7  0:00.00 ./proxy_server -i1000 -o1000 -w4
 2210 root       20   0  436M  255M  4848 S  0.0 13.7  0:11.19 ./proxy_server -i1000 -o1000 -w4
 2211 root       20   0  436M  255M  4848 S  0.0 13.7  0:22.96 ./proxy_server -i1000 -o1000 -w4
 2212 root       20   0  436M  255M  4848 S  0.0 13.7  0:26.07 ./proxy_server -i1000 -o1000 -w4
 2341 root       20   0  436M  255M  4848 S  0.0 13.7  0:26.89 ./proxy_server -i1000 -o1000 -w4
  846 root       20   0  436M  255M  4848 S  0.0 13.7  1:27.19 ./proxy_server -i1000 -o1000 -w4


连接已经全部断开了，只剩下与默认服务器的ip连接了
root@arm-64:~# lsof -p 846
COMMAND   PID USER   FD      TYPE             DEVICE SIZE/OFF   NODE NAME
proxy_ser 846 root  cwd       DIR              179,2     4096 150715 /usr/local/smargate/linux_arm64
proxy_ser 846 root  rtd       DIR              179,2     4096      2 /
proxy_ser 846 root  txt       REG              179,2   934312 150717 /usr/local/smargate/linux_arm64/proxy_server
proxy_ser 846 root  mem       REG              179,2  2698976 133497 /usr/lib/aarch64-linux-gnu/libcrypto.so.1.1
proxy_ser 846 root  mem       REG              179,2   564864 133889 /usr/lib/aarch64-linux-gnu/libssl.so.1.1
proxy_ser 846 root  mem       REG              179,2    75800 133282 /usr/lib/aarch64-linux-gnu/libnss_myhostname.so.2
proxy_ser 846 root  mem       REG              179,2    80616 132452 /usr/lib/aarch64-linux-gnu/libresolv-2.28.so
proxy_ser 846 root  mem       REG              179,2    22808 133883 /usr/lib/aarch64-linux-gnu/libnss_dns-2.28.so
proxy_ser 846 root  mem       REG              179,2    51640 133444 /usr/lib/aarch64-linux-gnu/libnss_files-2.28.so
proxy_ser 846 root  mem       REG              179,2  1439544 134652 /usr/lib/aarch64-linux-gnu/libc-2.28.so
proxy_ser 846 root  mem       REG              179,2    14560 134662 /usr/lib/aarch64-linux-gnu/libdl-2.28.so
proxy_ser 846 root  mem       REG              179,2   151656 133488 /usr/lib/aarch64-linux-gnu/libpthread-2.28.so
proxy_ser 846 root  mem       REG              179,2   136968 133778 /usr/lib/aarch64-linux-gnu/ld-2.28.so
proxy_ser 846 root    0r      CHR                1,3      0t0      4 /dev/null
proxy_ser 846 root    1w      CHR                1,3      0t0      4 /dev/null
proxy_ser 846 root    2u     unix 0x0000000063e55209      0t0  10703 type=STREAM
proxy_ser 846 root    3u     IPv4              24667      0t0    TCP arm-64.lan:51818->xxxxxxxxxxxxx (ESTABLISHED)
proxy_ser 846 root    4u  a_inode               0,11        0   2079 [eventpoll]

root@arm-64:~# netstat -anop|grep tcp
tcp        0      0 192.168.6.44:9993       0.0.0.0:*               LISTEN      820/zerotier-one     off (0.00/0/0)
tcp        0      0 127.0.0.1:9993          0.0.0.0:*               LISTEN      820/zerotier-one     off (0.00/0/0)
tcp        0      0 192.168.6.44:29994      0.0.0.0:*               LISTEN      820/zerotier-one     off (0.00/0/0)
tcp        0      0 192.168.6.44:20212      0.0.0.0:*               LISTEN      820/zerotier-one     off (0.00/0/0)
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      912/sshd             off (0.00/0/0)
tcp        0      0 0.0.0.0:1086            0.0.0.0:*               LISTEN      1493/python3         off (0.00/0/0)
tcp        0      0 192.168.6.44:55940      193.104.57.200:443      ESTABLISHED 850/v2ray            keepalive (3.69/0/0)
tcp        0      0 192.168.6.44:55936      193.104.57.200:443      ESTABLISHED 850/v2ray            keepalive (3.69/0/0)
tcp        0      0 192.168.6.44:51824      118.25.128.93:39001     ESTABLISHED 846/./proxy_server   off (0.00/0/0)
tcp        0      0 192.168.6.44:22         192.168.6.17:63164      ESTABLISHED 2229/sshd: root@pts  keepalive (15.44/0/0)
tcp        0      0 192.168.6.44:55930      193.104.57.200:443      ESTABLISHED 850/v2ray            keepalive (8.04/0/0)
tcp        0      0 192.168.6.44:56186      193.104.57.200:443      ESTABLISHED 850/v2ray            keepalive (8.04/0/0)
tcp        0      0 192.168.6.44:55966      193.104.57.200:443      ESTABLISHED 850/v2ray            keepalive (3.98/0/0)
tcp        0      0 192.168.6.44:55942      193.104.57.200:443      ESTABLISHED 850/v2ray            keepalive (9.32/0/0)
tcp6       0      0 :::9001                 :::*                    LISTEN      953/apache2          off (0.00/0/0)
tcp6       0      0 ::1:9993                :::*                    LISTEN      820/zerotier-one     off (0.00/0/0)
tcp6       0      0 :::22                   :::*                    LISTEN      912/sshd             off (0.00/0/0)
tcp6       0      0 :::1080                 :::*                    LISTEN      850/v2ray            off (0.00/0/0)
tcp6       0      0 :::12345                :::*                    LISTEN      850/v2ray            off (0.00/0/0)
tcp6       0      0 192.168.6.44:1080       192.168.6.17:63160      ESTABLISHED 850/v2ray            keepalive (9.06/0/0)
tcp6       0      0 192.168.6.44:1080       192.168.6.17:63165      ESTABLISHED 850/v2ray            keepalive (4.02/0/0)
tcp6       0      0 192.168.6.44:1080       192.168.6.17:63159      ESTABLISHED 850/v2ray            keepalive (3.69/0/0)
tcp6       0      0 192.168.6.44:1080       192.168.6.17:63151      ESTABLISHED 850/v2ray            keepalive (3.43/0/0)
tcp6       0      0 192.168.6.44:1080       192.168.6.17:63242      ESTABLISHED 850/v2ray            keepalive (8.30/0/0)
tcp6       0      0 192.168.6.44:1080       192.168.6.17:63149      ESTABLISHED 850/v2ray            keepalive (8.04/0/0)
root@arm-64:~# 


估计与speedtest-x这软件兼容存在问题，另外观察到测试时cpu差不多使用率达到了一段时间的100%，不知道是不是由于cpu繁忙导致处理不过来。

**Comment by lazy-luo** [comment]
测试了一下，暂时没有发现内存泄露，macOS上内存稳定在4-6M，linux-x86-64上内存稳定在6-7M。反复测试多次没有重现。

服务端：
sg服务端运行在macOS及linux x86_64上，同时安装speedtest-x（docker）
1、docker pull badapple9/speedtest-x
2、docker run -d -p 9001:80 -it badapple9/speedtest-x
客户端（sg ipv4 P2P）
1、电脑访问 http://手机ipv4:9001/
2、手机访问 http://localhost:9001/

**Comment by lilyok1234** [comment]
> 测试了一下，暂时没有发现内存泄露，macOS上内存稳定在4-6M，linux-x86-64上内存稳定在6-7M。反复测试多次没有重现。
> 
> 服务端： sg服务端运行在macOS及linux x86_64上，同时安装speedtest-x（docker） 1、docker pull badapple9/speedtest-x 2、docker run -d -p 9001:80 -it badapple9/speedtest-x 客户端（sg ipv4 P2P） 1、电脑访问 [http://手机ipv4:9001/](http://%E6%89%8B%E6%9C%BAipv4:9001/) 2、手机访问 http://localhost:9001/
> 
> cpu忙问题不大的，那是cpu性能跟不上，应该没影响 为了排除其它干扰，如果有空建议使用“干净”的系统测试一下

好的，那估计是我本地可能哪个服务引起的，我再观察观察找找原因，平时使用些ssh什么的服务还好，没发现内存存在很大的变化。
