### ISSUE TITLE
这配置不对吗？

### ISSUE THREAD

**Issue by Silver-Fang** [lazy-luo/smarGate#58]
![Screenshot_20211213_231855_com smarGate huawei](https://user-images.githubusercontent.com/33191697/145839164-f4ad0f17-d3d9-47b1-9a5c-9e303e83afe2.jpg)

**Comment by Silver-Fang** [comment]
![image](https://user-images.githubusercontent.com/33191697/145840729-9c9fa971-8213-4ddc-b106-c3a6340de3eb.png)

**Comment by lazy-luo** [comment]
1、配置成gpuserver的内网ip地址
2、确保rdp客户端电脑和手机在同一个局域网

**Comment by Silver-Fang** [comment]
> 1、配置成gpuserver的内网ip地址 2、确保rdp客户端电脑和手机在同一个局域网

IP配的肯定是内网的啊，局域网我只知道客户端和手机连的同一个WIFI

**Comment by lazy-luo** [comment]
ping一下网络吧
1、rdp客户端到手机 ping 10.20.193.147
2、GpuServer机器上到windwos rdp服务器 ping 10.100.217.2
如果猜的不错，至少有一个不通哦

**Comment by lazy-luo** [comment]
那就看看sg服务端正常启动否，或重启app
