### ISSUE TITLE
无法建立p2p连接

### ISSUE THREAD

**Issue by kangbeicai** [lazy-luo/smarGate#59]
![微信图片_20220211141851](https://user-images.githubusercontent.com/57837294/153545794-19837080-3983-420c-b02d-c0f3fc7212c2.jpg)
可以通过192.168.2.148:8096访问服务器资源，但是没有建立起p2p连接。
服务端的内网ip是192.168.50.165， ping手机IP(192.168.2.148)不通。

**Comment by zhouhuade** [comment]
这是来自本邮箱的自动回复邮件。你好，我已收到你的邮件，我将尽快给你回复。

**Comment by kangbeicai** [comment]
换成数据或者带ipv6的wifi可以建立ipv6的p2p了，可能是NAT类型的原因，但是用zerotier建p2p基本没什么问题。

**Comment by kangbeicai** [comment]
> tcp端口被q？是所有tcp端口都无法连接？如果是这种情况可以认为服务端就是NAT4，因此除非手机接入网络是NAT1-2才行 建议自行检测一下，另外最好将网络拓扑描述清楚，便于有效解决问题 另外需要注意的是：默认情况下官方代理会拒绝代理到国外ip，如有国外ip如无法p2p可自行创建私有代理

怎么检测手机的网络NAT类型？
我是学校的网络，宿舍分配公网ip，tcp端口出校以后会被墙，校内正常。 
宿舍的网络是 主路由 + 旁路由 + NAS，  主路由和旁路由都是用的op，在这三个设备上都部署服务器测试过。
客户端是校内办公室的无线网络时， 无法建立p2p连接。 但是校内是能正常访问到宿舍的tcp端口的。

另外我又测试了在我家的op旁路由做服务器，用宿舍的无线网做客户端时，能够建立p2p连接，但是用手机流量就不能。

**Comment by lazy-luo** [comment]
> > 一般无法P2P的情况比较多，实践中多半是NAT类型问题
> 
> 应该是NAT类型的原因了，办公室测试出来是NAT4，寝室是NAT3。 顺便问一下，为什么客户端做成只支持安卓呢， 将来有没有做linux/windows客户端的计划呢？

主要是便携性考虑，毕竟手机是随身携带的。有linux客户端主要是toB的
