### ISSUE TITLE
手机ipv6支持

### ISSUE THREAD

**Issue by hao86** [lazy-luo/smarGate#6]
服务端有ipv6，但是只出不进，ipv4 nat对称型，手机端ipv6全开放，ipv6不能直连走中转，作者似乎没有考虑到这种情况，所以提功能吧！

**Comment by lazy-luo** [comment]
实测这种情况是可以直连v6网络的，手机4G v6网络实测过电信/联通的，服务端电信宽带v6，服务端防火墙开启，只出不进。结论是可以成功。另外从设计上讲是也是充分考虑到这种情况的，手机端v6地址全局可路由无疑，请确认服务端v6地址是否能路由出去。

**Comment by hao86** [comment]
目前情况是：服务端可访问ipv6网站，手机端可接受服务端ssh直连（手机端开始sshd服务），但是手机端未显示直连的标志

**Comment by lazy-luo** [comment]
@hao86 为了便于定位问题，请提供详细信息。

**Comment by lazy-luo** [comment]
@hao86 另外，确保服务器端和客户端下载最新版本
