### ISSUE TITLE
openwrt报错

### ISSUE THREAD

**Issue by hisune** [lazy-luo/smarGate#60]
执行：
ldd ./proxy_server
```
        /lib64/ld-linux-x86-64.so.2 (0x7f3c5b727000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f3c5b727000)
        libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f3c5b727000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f3c5b727000)
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by ./proxy_server)
Error relocating ./proxy_server: mallopt: symbol not found
Error relocating ./proxy_server: malloc_trim: symbol not found
```

执行：
ln -s /lib/ld-musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2
ldd ./proxy_server
```
        /lib64/ld-linux-x86-64.so.2 (0x7f14f4640000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f14f4640000)
        libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f14f4640000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f14f4640000)
Error relocating ./proxy_server: mallopt: symbol not found
Error relocating ./proxy_server: malloc_trim: symbol not found
```

**Comment by zhouhuade** [comment]
这是来自本邮箱的自动回复邮件。你好，我已收到你的邮件，我将尽快给你回复。

**Comment by lazy-luo** [comment]
> 执行： ldd ./proxy_server
> 
> ```
>         /lib64/ld-linux-x86-64.so.2 (0x7f3c5b727000)
>         libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f3c5b727000)
>         libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f3c5b727000)
>         libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f3c5b727000)
> Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by ./proxy_server)
> Error relocating ./proxy_server: mallopt: symbol not found
> Error relocating ./proxy_server: malloc_trim: symbol not found
> ```
> 
> 执行： ln -s /lib/ld-musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2 ldd ./proxy_server
> 
> ```
>         /lib64/ld-linux-x86-64.so.2 (0x7f14f4640000)
>         libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f14f4640000)
>         libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f14f4640000)
>         libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f14f4640000)
> Error relocating ./proxy_server: mallopt: symbol not found
> Error relocating ./proxy_server: malloc_trim: symbol not found
> ```

请确保下载最新版本v0.30.4
