### ISSUE TITLE
mips版本openwrt提示Not a valid dynamic program

### ISSUE THREAD

**Issue by biankasyo** [lazy-luo/smarGate#62]
非常感谢您的项目，这边在使用#32 方法在openwrt路由器安装过程中，使用ldd ./proxy_server时提示Not a valid dynamic program。

**硬件环境:** TP-LINK WDR7500
**CPU:** QCA9558
**软件版本:** dynamic中mips v0.30.4 [linux_mips32.tar]（截图为mipsel，mips相同报错信息）

![image](https://user-images.githubusercontent.com/10541658/162613813-b87296da-3034-4517-b37b-51cff4251df2.png)

**Comment by lazy-luo** [comment]
uname -a 先确认系统版本及架构

**Comment by biankasyo** [comment]
> uname -a 先确认系统版本及架构 试试：readelf -d ./proxy_server | grep NEEDED 另外，请将详细步骤描述一下，便于提高问题解决效率

感谢回答，uname -a确认是mips（如下截图），且为mips32。
![image](https://user-images.githubusercontent.com/10541658/162628966-cfe2f784-2b3a-441b-8071-05e053ff01a5.png)

readelf -d ./proxy_server | grep NEEDED在openwrt中貌似无法执行，好像没有该命令的相关软件包。。
![image](https://user-images.githubusercontent.com/10541658/162629008-f4f4b6ca-f693-47c5-bcbe-622558b53036.png)

详细步骤如下：
1、在centos cd /tmp
2、在centos wget https://github.com/lazy-luo/smarGate/raw/master/dynamic/linux_mips32.tar
3、在centos tar -xvf linux_mips32.tar
4、在centos 重新压缩目录/tmp/linux_mips32为archive.tgz
5、在openwrt cd /tmp 
6、将archive.tgz传到openwrt /tmp目录下
7、在openwrt tar -zxvf archive.tgz
8、在openwrt cd /tmp/linux_mips32
9、在openwrt ldd ./proxy_server 报错Not a valid dynamic program
10、在openwrt ./proxy_server 报错line 1: syntax error: unexpected word (expecting ")")

之所以先在centos解压再重压缩，是因为openwrt下不知为何tar相同命令无法直接解压，提示invalid tar magic
![image](https://user-images.githubusercontent.com/10541658/162629494-d6220a32-0199-4e31-9794-8acf9a7b1b7d.png)

**Comment by lazy-luo** [comment]
问题应该是交叉编译环境c运行库差异造成的，0.30.3版本采用的是uClibc库进行编译，无法兼容musl。0.30.4采用musl库进行编译

**Comment by biankasyo** [comment]
> 

非常感谢大神编译解答，软连接后貌似还是有问题，提示Unwind_Find_FDE: symbol not found

![image](https://user-images.githubusercontent.com/10541658/162663547-47f71921-1558-4976-8350-45911f02d714.png)

我是将 ln -s /lib/ld-musl-mips-sf.so.1 /lib/ld.so.1，openwrt lib如下
![image](https://user-images.githubusercontent.com/10541658/162663679-6e2f7fe2-cea4-44cc-b222-ffd593f7e066.png)

ld-musl-mips-sf.so.1连接的是libc.so

**Comment by lazy-luo** [comment]
请从网盘mini/for-test/目录下载编译版本，去掉了gcc静态编译选项

**Comment by biankasyo** [comment]
> 请从网盘mini/for-test/目录下载编译版本，去掉了gcc静态编译选项

非常感谢！目前程序已可运行，但是提示OpenSSL的lib库未找到，详情如下：
![image](https://user-images.githubusercontent.com/10541658/162912922-43cedad7-ec77-42e7-8018-f10b1a720bb1.png)

这边已安装OpenSSL，对应库目录在/usr/lib下，目录内容如下：
![image](https://user-images.githubusercontent.com/10541658/162913921-627e31de-0345-405b-a884-840255073a63.png)

配置文件如下：
![image](https://user-images.githubusercontent.com/10541658/162913485-03ba487c-1747-4c30-b886-78dadb693ed1.png)

麻烦帮忙看一下，感谢！

**Comment by lazy-luo** [comment]
缺少openssl库，装上就行了：
1、apt-get install -y openssl
2、安装好后，找到 libssl.so 和 libcrypto.so 的文件名及全路径，配置到配置文件中即可

**Comment by biankasyo** [comment]
> 缺少openssl库，装上就行了： 1、apt-get install -y openssl 2、安装好后，找到 libssl.so 和 libcrypto.so 的文件名及全路径，配置到配置文件中即可 可以使用：cd / && find ./ -name "libssl.so*" 2>/dev/null 或者: ldd $(which openssl)

收到，实在麻烦。貌似还是出现库路径错误。。。 T T

已安装OpenSSL并将对应库目录配置如下：
libssl目录配置为/usr/lib/libssl.so.1.1
libcrypto目录配置为/usr/lib/libcrypto.so.1.1

使用ldd $(which openssl)截图如下：
![image](https://user-images.githubusercontent.com/10541658/162922062-f9e56b2b-5525-4b16-b361-816bdc5ee6a2.png)

确定OpenSSL已安装
![image](https://user-images.githubusercontent.com/10541658/162922104-e74b4c35-1400-441c-b995-7dcfba2f2ab7.png)

目前报错信息：
![image](https://user-images.githubusercontent.com/10541658/162922147-403fad78-85b0-4f5c-83de-5a5aa2863f4e.png)

**Comment by lazy-luo** [comment]
> 缺少openssl库，装上就行了：
> 1、apt-get install -y openssl
> 2、安装好后，找到 libssl.so 和 libcrypto.so 的文件名及全路径，配置到配置文件中即可
> 可以使用：cd / && find ./ -name "libssl.so*" 2>/dev/null
> 或者: ldd $(which openssl)

呃，看到了，有对应的文件，貌似目录也是对的。建议先看看openssl依赖的位置，如果是一致的，配置文件中就把目录去掉只写名字试试

**Comment by lazy-luo** [comment]
基本上是你openssl安装有问题，运行 openssl --version 能正常否

**Comment by biankasyo** [comment]
> 基本上是你openssl安装有问题，运行 openssl --version 能正常否

收到，多谢大神。可能下个月才能继续搞，我是远程ssh登录，装软件时没注意路由器16M Flash满了，自动系统分区变为只读。。。需要下个月回去刷机再看T T
