### ISSUE TITLE
#远程开机

### ISSUE THREAD

**Issue by wzf9** [lazy-luo/smarGate#63]
背景：已经借助远程唤醒工具实现局域网下的远程开机。

期望：跨局域网下的远程开机：借助smarGate,无公网IP下的win10电脑A，远程开机另一个内网下的win10电脑B。

详情：请教一下，我现在在内网下的win10电脑A上开启了服务端模式，安卓手机上也成功连接了，看到了win10电脑B上线了。接下来，如何远程开机？（是通过安卓手机上的SSH服务吗？本人计算机小白，还望作者不吝赐教~非常感谢)

**Comment by lazy-luo** [comment]
远程开机是通过UDP广播实现的，SG支持tcp/UDP端口映射但不支持UDP广播

**Comment by wzf9** [comment]
谢谢作者~

**Comment by lazy-luo** [comment]
SG本身不支持，但不代表无法实现。
话说简单写个c/s模式的局域网开机服务，然后你就可以使用SG远程开机了

**Comment by wzf9** [comment]
谢谢作者~不过我都是头一次听说，更别说自己编写c/s模式的局域网开机服务了~哈哈哈
