### ISSUE TITLE
想问一下有Linux,win版本的客户端吗？

### ISSUE THREAD

**Issue by 201841301322** [lazy-luo/smarGate#64]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lazy-luo** [comment]
后续版本将推出服务端组网能力，将不在有服务器版本的客户端需求了

**Comment by lilyok1234** [comment]
期待，目前个人使用的场景主要是公司网连到家里的，目前联通和电信的手机网络基本都是NAT4的，很难p2p直连，所以我每次都是手机连wifi（能够p2p直连），然后再公司电脑连手机，最终连到家里。但是这种延迟略高啊。如果能服务器直连那就太好了。目前我是以zerotier为主，SG为辅

**Comment by zhouhuade** [comment]
这是来自本邮箱的自动回复邮件。你好，我已收到你的邮件，我将尽快给你回复。
