### ISSUE TITLE
p2p成功连接两分钟之后空闲自动断开连接，如何保证两分钟之后仍然保持连接？

### ISSUE THREAD

**Issue by Gudischroas** [lazy-luo/smarGate#66]
用p2p成功连接远程桌面之后两分钟就会断连，然后访问点就会掉到官方代理访问，无法重新再用p2p进行重连。有什么方法可以在成功p2p连接远程桌面之后不断连，使p2p连接不空闲从而避免断连？

**Comment by lazy-luo** [comment]
1、确保版本不是太旧的，建议更新到最新版本
2、空闲断开后，一般会自动重连（最多尝试3次，v4连接失败后不支持重试，v6连接失败后会有刷新按钮可点击重试），如果两端网络没有变化，重连也能成功p2p的
3、也可以退出app再重启，也就手划一下的事
4、使用中连接会一直有效的，不会空闲断开
有一种情况重连会失败：重连时服务端信令连接正好也超时退出了；这种情况下等待10秒左右重试就行了
希望能帮到你
