### ISSUE TITLE
服务端与客户端在同一内网下无法打通

### ISSUE THREAD

**Issue by biankasyo** [lazy-luo/smarGate#69]
概述：
mips路由器运行服务端，手机客户端在在mips服务端内网下，无法使用手机APP设定的mips服务端访问上级路由网关，但可以使用手机APP自身客户端设定映射访问

服务端环境：
WDR7500 mips openwrt路由器
内网IPV6
NAT4 IPV4
mips服务端网关地址：192.168:9.1

手机APP端环境：
小米9 Android11
与与服务端处于相同内网
内网IP 192.168.9.103

问题：
服务端设定端口8787，指向上级路由192.168.8.1，APP客户端访问失败；
客户端设定端口8686，指向上级路由192.168.8.1，APP客户端访问成功；
APP客户端访问同内网服务端服务失败

补充：客户端通过服务端访问服务端自身网关即192.168.9.1也失败

![Screenshot_2022-06-29-00-59-47-108_com smarGate huawei](https://user-images.githubusercontent.com/10541658/176239329-02570e33-6b45-463b-96a5-6d7a1b532cf7.jpg)

![Screenshot_2022-06-29-00-41-38-711_com android browser](https://user-images.githubusercontent.com/10541658/176239458-bb9c7b3f-35f3-4430-8c73-5e31afce2791.jpg)

![Screenshot_2022-06-29-00-41-34-213_com android browser](https://user-images.githubusercontent.com/10541658/176239558-ea85e56d-f0b7-4125-b866-4099676b9822.jpg)

**Comment by lazy-luo** [comment]
根据你的配置；
**A、先确认隧道是否正常：**
1、可以打开openwrt的22端口，app上对应访问点配上映射。如能正常访问则代表隧道没问题，否则大概率是下面1）中的情况。
**B、如隧道正常，再逐步排查：**
1、通过app  http://localhost:8787/ 的访问，等同于在mips路由器上访问 http://192.168:8.1/ ，首先看看在路由器上能否正常访问
**C、如果隧道有问题则：**
1、确认服务端是否正常运行，同时客户端是否授予了后台运行权限

最后：http访问最好是选择http协议，否则部分网站会出问题

**Comment by lazy-luo** [comment]
此BUG仅在大端机器上存在，已修复，请移步网盘链接进行修复后版本下载测试：
https://pan.baidu.com/s/14Iq60kxHW711NVoCVKWySg

**Comment by biankasyo** [comment]
收到，多谢大神，外网局域网隧道均已通！
另外还有一个问题：
同局域网下隧道已通，但速度较慢，貌似非P2P直连（手机客户端APP显示P2P）

**Comment by lazy-luo** [comment]
> 收到，多谢大神，外网局域网隧道均已通！
> 另外还有一个问题：
> 同局域网下隧道已通，但速度较慢，貌似非P2P直连（手机客户端APP显示P2P）

建议测一下速吧，或者与其他穿透软件对比一下。一般情况下都是网络自身的原因

**Comment by biankasyo** [comment]
收到，我先用公网IP建立了代理服务器使用下，有时间继续测试，谢谢作者耐心解答分享！
