### ISSUE TITLE
ios客户端能有吗

### ISSUE THREAD

**Issue by mljxxx** [lazy-luo/smarGate#7]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lazy-luo** [comment]
有IOS版本，之前属于自用的，设备未越狱，开发者证书有效期太短，经常需要重装。。。在android版稳定前，暂无计划上appstore

**Comment by mljxxx** [comment]
太可惜了，用安卓手机开热点，rdp延迟有点高

**Comment by lazy-luo** [comment]
下次版本更新时打包一个IOS客户端上来，暂时只有越狱设备能用。
rdp握手阶段会受延迟影响，实测p2p下用起来还是非常顺畅的，4G网络下能达到稳定的1MB+的速度，使用感知和本机无明显区别。另外目前的延迟更多的是受v6网络本身影响，待isp优化好v6网络后估计就好了。

**Comment by mljxxx** [comment]
我的设备没有越狱，期待正式版，暂时用zerotier，本来想用frp但是带宽太贵了，xtcp打不通
