### ISSUE TITLE
zsh: no such file or directory: ./proxy_server

### ISSUE THREAD

**Issue by lcl-101** [lazy-luo/smarGate#70]
![image](https://user-images.githubusercontent.com/13747322/188352891-8d6dc266-1d35-4d5b-9531-8ad03677258d.png)

**Comment by zhouhuade** [comment]
这是来自本邮箱的自动回复邮件。你好，我已收到你的邮件，我将尽快给你回复。

**Comment by lazy-luo** [comment]
1、首先确定下载适合架构的版本
2、如果没有执行权限请用chmod +x proxy_server添加权限
