### ISSUE TITLE
只能使用手机作为中转节点吗?

### ISSUE THREAD

**Issue by JsonSong89** [lazy-luo/smarGate#73]
比如我家里面的nas(linux)安装了proxy_server 
然后办公室的windows系统可以作为节点访问家里的nas服务吗? 
我用手机是可以的,但是我想直接windows和nas进行穿透,不使用手机
如果可以,配置应该是怎么样的? 好像只有手机里可以配置端口的代理

**Comment by lazy-luo** [comment]
1、SG推荐使用手机作为中转节点，主要是考虑便携性及安全性。
2、SG最新版本（>= v0.31）支持服务端间穿透访问，配置完成后无需手机中转：
配置统一在app上进行，只是在远程ip后加@index指向特定序号服务端
app端将在能p2p或有自定义代理的情况下每10秒刷新状态（否则不刷新---不刷新状态不代表服务端不能访问）
具体情况可参见<<快速上手手册>>第五小结（https://github.com/lazy-luo/smarGate/wiki/快速上手手册）

**Comment by JsonSong89** [comment]
感谢解答
不过我发现好像并不行  
我现在网络如图,wifi手机,windows处于同一网段,配了一个本地穿透 1080 ,pc已经可以通过手机ip+1080访问nas了,
然而使用pc_ip+1098,还是不能访问nas  
![image](https://user-images.githubusercontent.com/4394916/192269310-5f4d8d86-2731-4edd-9274-055d7d042e49.png)

![image](https://user-images.githubusercontent.com/4394916/192268778-a77f3627-d07d-498a-bbb3-809347a9ebfc.png)

**Comment by JsonSong89** [comment]
按理说我nas和手机都打通了,所以网络应该是没啥问题的吧
就是不知道为啥还是显示 x

**Comment by lazy-luo** [comment]
显示X说明你的“of_pc”访问点无法和“hm_pve”节点P2P

**Comment by JsonSong89** [comment]
> 显示X说明你的“of_pc”访问点无法和“hm_pve”节点P2P 和你手机网络无关

我手机用的wifi,和of_pc一个网段啊 为什么手机代理可以成功呢

**Comment by lazy-luo** [comment]
服务端组网只能在如下两种情况下使用：
1、能成功P2P
2、有自定义代理
你手机能访问，因为走的是官网代理，手机到“hm_pve”明显也无法P2P啊

**Comment by JsonSong89** [comment]
> 服务端组网只能在如下两种情况下使用： 1、能成功P2P 2、有自定义代理 你手机能访问，因为走的是官网代理，手机到“hm_pve”明显也无法P2P啊

所以是只有手机端能使用官网代理,其他平台的服务端,如果无法打通p2p,也不能走官网代理了吗?

**Comment by JsonSong89** [comment]
> 是的，官网代理带宽小，感知不好的。话说宽带搞个v6不是很容易吗？

就算要v6,得两边都有v6吧
家里的网络用了v6,会和clash的一些规则冲突,加上不知道有啥用,就没开
公司的话,基本我就没见哪些公司开了v6的,本来就防着外网呢.

**Comment by JsonSong89** [comment]
嗯 我再试试p2p吧  
或者我有vps,自己搭个代理是不是也能解决问题?

**Comment by lazy-luo** [comment]
> 嗯 我再试试p2p吧
> 或者我有vps,自己搭个代理是不是也能解决问题?

自定义代理可以解决问题，关键要看带宽

**Comment by JsonSong89** [comment]
好的 我主要目的还是只是一些文档存取,对带宽要求不高 
不过我还是先试试p2p 看能不能搞通.

**Comment by JsonSong89** [comment]
![image](https://user-images.githubusercontent.com/4394916/192283224-2620e11f-40f0-4d93-9644-2c36cdfb90fa.png)
我的nas网络居然是最高等级的 Full cone NAT
