### ISSUE TITLE
在手机端配置了对应的端口，但在使用moonlight时，提示检查防火墙转发规则

### ISSUE THREAD

**Issue by MeditatorV** [lazy-luo/smarGate#75]
现象：
我在使用smargate，已配置了相应的端口，但使用moonligh时，moonligh报以下错误：
![image](https://user-images.githubusercontent.com/47035563/193837450-5bd52b91-9a21-4a45-9bc2-066001a8229a.png)
以下是smargate的配置截图：
![image](https://user-images.githubusercontent.com/47035563/193835666-b572f35a-739a-4794-b7ea-809db389cf33.png)
下面连接是moonligh的配置说明：
https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide
其中此段说明需要配置的端口：
![image](https://user-images.githubusercontent.com/47035563/193838563-cb9a4720-f25a-488c-985b-16e059a722b8.png)

对比：
控制PC与被控PC不变的情况下：
1、走smargate时，使用远程桌面控制被控PC，正常。
2、使用外网时使用moonligh，正常可用
3、但走smargate时，使用moonligh，报提示检查防火墙转发规则（如上报错截图）

希望大神指点一二，如何配置防火墙转发规则，谢谢

**Comment by MeditatorV** [comment]
感谢回复

**Comment by lazy-luo** [comment]
> 请问如何在两个局域网分别运行SG服务端？可否简单说明下，谢谢
> 另moonlight是己开发好的软件，无法配置成RCP over TCP，希望SG的后续版本可以支持RTSP协议，感谢

分别运行服务端即可，需要注意的是配置文件中index序号不要重复。配置成功后在app上会看到这两个“访问点”，根据实际需要配置即可
