### ISSUE TITLE
APP能否增加一个通知栏的快捷方式磁贴？

### ISSUE THREAD

**Issue by LostMyMind** [lazy-luo/smarGate#76]
**Describe the solution you'd like**
代理类工具，比如SSR、surfboard与clash之类的安装时会在通知栏生成一个磁贴，用户点击磁贴即可快速打开代理，咱们有没有考虑也做一个磁贴，按一下开启服务，再按一下关闭服务？

**Additional context**
1 安卓的磁贴
![1](https://user-images.githubusercontent.com/57167544/201481598-3a5612e1-6545-4cae-83f9-4ec444dfae5c.jpg)
2 第四排最左边就是surfboard的磁贴，按一下自动启动代理，再按一下就关闭，无需到桌面来启动app，如果偶尔使用，这样会方便一些。 
![2](https://user-images.githubusercontent.com/57167544/201481673-0bdb0cac-8adc-46a0-acd7-30865d1cc8ba.jpg)
![3](https://user-images.githubusercontent.com/57167544/201481682-7b39dfd5-633d-413d-9578-a2859f663cb0.jpg)

**Comment by zhouhuade** [comment]
这是来自本邮箱的自动回复邮件。你好，我已收到你的邮件，我将尽快给你回复。

**Comment by lazy-luo** [comment]
对于Android 客户端而言，不是简单的“开启“及”关闭“逻辑，没有明确场景暂不支持
对于Android 服务端，磁贴能带来便利性，后续版本可酌情考虑

**Comment by LostMyMind** [comment]
> 对于Android 客户端而言，不是简单的“开启“及”关闭“逻辑，没有明确场景暂不支持 对于Android 服务端，磁贴能带来便利性，后续版本可酌情考虑

你好，我想问一下，我现在已经建好了自建服务器，有什么方法能看走的是自建服务器的代理吗？
以及我每次打开app，把模式切换点成灰色，发现官方代理是默认打开的，能在后续把这个选项改为默认与上次设置一致吗？

**Comment by lazy-luo** [comment]
1、自定义代理生效时对应“访问点”会有不同色条区分
2、官方代理默认就是打开的，但是如果自定义代理生效或p2p成功时不会走代理。
后续版本可以把这个选项的配置持久化

**Comment by LostMyMind** [comment]
> 1、自定义代理生效时对应“访问点”会有不同色条区分 2、官方代理默认就是打开的，但是如果自定义代理生效或p2p成功时不会走代理。 后续版本可以把这个选项的配置持久化

好的，谢谢你了。

**Comment by lazy-luo** [comment]
> > 1、自定义代理生效时对应“访问点”会有不同色条区分 2、官方代理默认就是打开的，但是如果自定义代理生效或p2p成功时不会走代理。 后续版本可以把这个选项的配置持久化
> 
> 好的，谢谢你了。

选项已做持久化，暂未合并到主版本，如有需要请到百度网盘下载（仅需下载app）https://pan.baidu.com/s/14Iq60kxHW711NVoCVKWySg
