### ISSUE TITLE
smargate有windows客户端吗

### ISSUE THREAD

**Issue by gjthbc** [lazy-luo/smarGate#79]
如题

**Comment by lazy-luo** [comment]
实际上无需其它平台客户端
新版本SG支持在APP上配置服务端间端口映射，服务端间映射配置生效后就可以直接在特定服务端访问其它服务端所在内网，无需APP中转

ps：可在头条或抖音搜索“SG 内网穿透”，有简要配置教学视频

**Comment by Dolphin4mi** [comment]
并没有找到任何关于APP上配置服务端间端口映射，无需APP中转特定服务端的方法。请问哪里有？

**Comment by lazy-luo** [comment]
见“快速上手手册”
