### ISSUE TITLE
p2p的成功率好像不太高，手机电脑同一个wifi下大部分情况还是走的代理服务器而不是p2p，很少数情况才会显示p2p连成功。不过内网穿透还是非常好用的，希望大佬可以增加一个分组管理和备注描述的功能，设置的端口映射多了很难想起来是干什么用的了

### ISSUE THREAD

**Issue by shuaigekda** [lazy-luo/smarGate#80]
电脑手机连同一wifi，smargate会显示经过代理服务器，带宽很低，而用别的p2p软件很快就会显示p2p连接成功

**Comment by zhouhuade** [comment]
这是来自本邮箱的自动回复邮件。你好，我已收到你的邮件，我将尽快给你回复。

**Comment by lazy-luo** [comment]
> 电脑手机连同一wifi，smargate会显示经过代理服务器，带宽很低，而用别的p2p软件很快就会显示p2p连接成功

1、同一wifi下任然默认优先ipv6，如果ipv6地址过期或其它原因会导致局域网无法P2P。可以尝试打开app上v4-only开关，同一内网可秒连成功。
2、分组管理后续版本计划支持，但也会限制分组数量。每条映射配置将支持短描述

**Comment by shuaigekda** [comment]
感谢回复，我试了手机和电脑同一内网手机app关闭ipv6，尝试了20次，p2p成功13次

**Comment by lazy-luo** [comment]
> 感谢回复，我试了手机和电脑同一内网手机app关闭ipv6，尝试了20次，p2p成功13次，7次自定义代理，不知道是高是低。但是一旦走代理服务器app好像就不会尝试p2p连接了，只能关闭后台再打开

是的，一旦代理先连上，在下一个重试周期就不在尝试P2P了

**Comment by lazy-luo** [comment]
> 如果能在代理连接的情况下，每隔十秒二十秒尝试p2p连接就好了，或者增加一个参数可以自选

另外由于服务端控制连接会超时断开，此时无法p2p协商，需要等待10秒左右。一般来讲重试3次无果基本就无法p2p，其实这都是避免无效流量压力的手段。

**Comment by shuaigekda** [comment]
好的，谢谢大佬回复
