### ISSUE TITLE
realme手机无障碍功能打不开，点击开关之后没反应还是灰色的

### ISSUE THREAD

**Issue by shuaigekda** [lazy-luo/smarGate#81]

**Comment by zhouhuade** [comment]
这是来自本邮箱的自动回复邮件。你好，我已收到你的邮件，我将尽快给你回复。

**Comment by shuaigekda** [comment]
https://user-images.githubusercontent.com/96943128/224290402-da59faec-35e8-4dc0-9229-215ee3d1cf22.mp4

**Comment by lazy-luo** [comment]
“无障碍”功能仅用于app服务端。你需要：
1、将app配置成服务端模式
2、运行app
