### ISSUE TITLE
P2P 打洞实现方式

### ISSUE THREAD

**Issue by zard1152** [lazy-luo/smarGate#82]
感谢您开发的 smarGate, 我对其中的 P2P 实现方式非常感兴趣，想要了解一下它的工作原理。您能分享一下关于P2P连接是如何建立和维护的技术细节吗？我查了一下目前的辅助打洞方式, 一种是需要一个公众IP来交换 peer 间的信息, 一种是 DHT 分布储存. 请问这款软件是通过你们的公共服务器实现信息交换吗.

**Comment by lazy-luo** [comment]
P2P协商其实是个较古老的问题，没有太多技术含量；目前版本使用你说的第一种方式

SG实现中将这类交互叫做“信令”，采用信令和数据传输分离的设计方式，信令承载服务器设计上是多点可分布式的

**Comment by zard1152** [comment]
明白, Thanks, Close
