### ISSUE TITLE
Android4.4可以安装但是打开一直卡死

### ISSUE THREAD

**Issue by PubutLi** [lazy-luo/smarGate#88]
CPU: 高通410 安卓版本: 4.4 机型: 纸盒 ROOT情况: 已root
另外想知道楼主这个应用是否可以让同一个手机既做服务端又做客户端，
比如手机开启4g网络和热点，内网其他设备连接这个热点并已分配到一个本地的ipv6地址，
让这个本地的ipv6地址上的服务可以暴露到公网，这样的场景可以实现吗？Thank you！

**Comment by lazy-luo** [comment]
1、4.4版本过老，未做兼容性验证。
2、目前手机app要么是客户端模式要么是服务端模式，如果设备支持双开可以尝试一下
3、手机服务端（A）的端口可以映射到另一个服务端（B）上，如果B有公网ip则能直接公网访问
4、服务端间远程端口映射只支持ipv4
