### ISSUE TITLE
注册成功返回的服务ID如何再次查看？

### ISSUE THREAD

**Issue by colemanlee** [lazy-luo/smarGate#9]
注册成功返回的服务ID如何再次查看？
注册成功后没来得及记录，后来找不到在哪再次查看了。

**Comment by lazy-luo** [comment]
看不到了哦，这个id是和你的用户名绑定的，后续版本登录后增加一个查看id的功能吧。目前只能后台手工找回，可加vx

**Comment by lazy-luo** [comment]
下载网盘新版本，在编辑模式（关闭“自动刷新”）中可以显示当前用户ID。
