### ISSUE TITLE
自建服务器可以不用注册吗？

### ISSUE THREAD

**Issue by sunlewuyou** [lazy-luo/smarGate#91]
自建服务器搭建也必须要在手机app上注册吗？可以不用注册吗？毕竟是用自己的服务器嘛。

**Comment by lazy-luo** [comment]
自建服务器无需注册

**Comment by lazy-luo** [comment]
> @lazy-luo 谢谢回复，那我理解的意思就是自建代理服务器的话，使用手册里第一步的操作就可以不做了对吧？
> 
> > 1、下载app && 注册新用户
> > 下载android app（app-release.apk包含客户端和服务端）支持armv7及arm64 cpu架构
> > 注册新用户（邀请码必填，为数字，可任意填。ps：如果必填信息未填完整,或包含中文字符，会注册失败）
> > 注册成功后请务必记住返回的服务ID(N) 【重要】：注册成功后务必在1小时内完成首次登录
> 
> 如果是不用做第一步注册用户了，那下面的配置又该如何改动？
> 
> ```
>   <?xml version="1.0" encoding="GBK"?>
>     <app-config code="PROXY" name="proxy-server">
>         <app-parameter>
> 	        <proxy-service-port value="9001"/>
> 		<owner-id value="xxxx" />
> 		<access-token value="nnnnn"/>
> 		<ssl-create-certfile value="true" />
>           
>        </app-parameter>
>        <moudle-parameter>
>         <log-level value="LOG_ERROR"/>
>         <log-write-mode value="CONSOLE_ONLY"/>
>       </moudle-parameter>
>   </app-config>
> ```
> 
> 看了视频后才发现自建代理服务器也必须要通过官方服务器提供认证服务，我还以为可以完全不需要官方服务器了，原来只是不需要它转发数据了。理解错误~

自建代理服务器**不会**通过官方服务器认证的，只有app客户端和服务端需要认证。代理服务器通过自定义的token进行安全认证

**Comment by lazy-luo** [comment]
> @lazy-luo 是的，app客户端和服务端需要认证，我的意思是不是以后可以不依赖官方服务器认证？比如以后官方服务器万一停止服务了，那是不是用户部署好的服务就都不能用了呢？

目前SG的设计是面向运营友好的，后续版本计划推出共建共享机制，大家贡献资源，分布式设计就不存在这种情况了，理论上只要有一定的用户基数就不会用不了
