### ISSUE TITLE
Windwos下启动服务后怎么关闭？

### ISSUE THREAD

**Issue by yangpin97** [lazy-luo/smarGate#95]
启动：cmd-->proxy_server.exe -i1000 -o1000 -w8 （另外这些参数啥意思）
关闭：？

**Comment by zhouhuade** [comment]
这是来自本邮箱的自动回复邮件。你好，我已收到你的邮件，我将尽快给你回复。

**Comment by lazy-luo** [comment]
> 启动：cmd-->proxy_server.exe -i1000 -o1000 -w8 （另外这些参数啥意思） 关闭：？

-i参数指定最大入站连接数量，-o参数指定最大出站连接数量，-w参数指定工作线程数（一般小于2倍cpu数量）
关闭使用“任务管理器”，找到proxy_server进程，结束即可

**Comment by yangpin97** [comment]
@lazy-luo OK

**Comment by yangpin97** [comment]
更新了一个博客，自己的一些总结和问题[多链路聚合（p2p+Proxy）模式-内网穿透-无需公网IP！](https://yydy.link:2023/archives/1090.html)
