### ISSUE TITLE
ISTORE OS(CPU是I3-1215U)运行报错

### ISSUE THREAD

**Issue by KINGFIGHTBOY** [lazy-luo/smarGate#96]
这个是错误信息![Image_1697451946876.png](https://github.com/lazy-luo/smarGate/assets/33369208/88a58ec9-ea91-4fa4-8ede-87ba55c50ad2)

我使用这些版本都报错![Image_1697451949041.png](https://github.com/lazy-luo/smarGate/assets/33369208/da10d74c-76e3-402c-b896-9e212f33796b)

**Comment by KINGFIGHTBOY** [comment]
这个是程序的路径![Image_1697452310103.png](https://github.com/lazy-luo/smarGate/assets/33369208/f1432159-e349-4f16-b400-650dcd95555e)

**Comment by lazy-luo** [comment]
1、i3-1215U应该是x86_64架构cpu，可运行name -a确认
2、ldd ./proxy_server查看依赖
3、ls -alt /lib/ld-musl* 确认c库版本
4、根据2）的输出决定软连接创建命令

**Comment by KINGFIGHTBOY** [comment]
> 1、i3-1215U应该是x86_64架构cpu，可运行name -a确认
> 2、ldd ./proxy_server查看依赖
> 3、ls -alt /lib/ld-musl* 确认c库版本，附上ls -alt /lib输出
> 4、根据2）的输出决定软连接创建命令

系统是x86_64的linux，以下是相关信息
![Image_1697501738345.png](https://github.com/lazy-luo/smarGate/assets/33369208/36502ec3-5c8e-44aa-a164-7e278ca690ab)

**Comment by KINGFIGHTBOY** [comment]
> 1、i3-1215U应该是x86_64架构cpu，可运行name -a确认
> 2、ldd ./proxy_server查看依赖
> 3、ls -alt /lib/ld-musl* 确认c库版本，附上ls -alt /lib输出
> 4、根据2）的输出决定软连接创建命令

1.系统是x86_64的linux
2.查看依赖提示缺失ld-linux-x86_64.so.2
3.这个是详细信息![Image_1697502024202.png](https://github.com/lazy-luo/smarGate/assets/33369208/938c1646-e378-4e00-b8b1-6a170870f672)

**Comment by KINGFIGHTBOY** [comment]
> 1、i3-1215U应该是x86_64架构cpu，可运行name -a确认
> 2、ldd ./proxy_server查看依赖
> 3、ls -alt /lib/ld-musl* 确认c库版本，附上ls -alt /lib输出
> 4、根据2）的输出决定软连接创建命令

大佬问题解决了
![Screenshot_2023-10-17-08-33-39-736_com.smarGate.huawei.jpg](https://github.com/lazy-luo/smarGate/assets/33369208/e7515581-01e1-4c51-8bb3-95eafd0b52ad)

根据这个来操作的![Image_1697502862928.png](https://github.com/lazy-luo/smarGate/assets/33369208/883a5c1f-3c63-4489-b772-b4b9af0a7b88)

**Comment by lazy-luo** [comment]
> > 1、i3-1215U应该是x86_64架构cpu，可运行name -a确认
> > 2、ldd ./proxy_server查看依赖
> > 3、ls -alt /lib/ld-musl* 确认c库版本，附上ls -alt /lib输出
> > 4、根据2）的输出决定软连接创建命令
> 
> 大佬问题解决了 !

你的环境关键就是两条shell命令：
ln -s /lib /lib64
ln -s /lib/ld-musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2

请及时关闭issue
