### ISSUE TITLE
mipsel架构的openwrt运行出现Illegal instruction

### ISSUE THREAD

**Issue by lfznnzq** [lazy-luo/smarGate#97]
mipsel架构的openwrt官方固件默认没有开启fpu，运行时出现Illegal instruction后停止

![QQ图片20231019123918](https://github.com/lazy-luo/smarGate/assets/11658987/e042c800-9bf0-4e63-94e3-dcd7e257ad93)

**Comment by lazy-luo** [comment]
1、确认本地musl库版本后缀是sf还是hf
2、不加LD_PRELOAD-LibCIYptO.30.1.2:116881.S0.1.2 直接运行
