### ISSUE TITLE
可否增加选项，设置手机端向服务器连接时使用的端口？

### ISSUE THREAD

**Issue by ouchyoungchina** [lazy-luo/smarGate#99]
目前单位的网络没有IPV6，家里有公网IPV4，并且打开了upnp，偶尔能实现p2p连接，网速明显很好，但不稳定，时常会获取不到p2p连接。后来试着把手机设置成为DMZ，发现能稳定拿到p2p。所以，应该是upnp不能确保每次都映射端口成功。能否在手机端增加选项，固定手机连接时使用的端口，这样可以直接在路由器上做端口映射。谢谢！

**Comment by zhouhuade** [comment]
这是来自本邮箱的自动回复邮件。你好，我已收到你的邮件，我将尽快给你回复。

**Comment by lazy-luo** [comment]
1、SG不会使用upnp
2、p2p理论能成功但实际不通，大部分情况下原因是防火墙策略（特别是商用防火墙），还有就是重连时恰逢信令连接断开（大概有10秒窗口）
3、手动重连的方法（不重启APP）：编辑模式下，切换一下ipv4-only开关（打开后再关闭），然后app会尝试重连----这其实是个bug，感觉有用就不改了
4、有关指定协商端口，可以在服务端配置negotiation-port选项，具体见github“附录-》更新历史-〉2020-04-30更新到v0.26”
